#### First, I will state the libraries needed to work in the project.

In [1]:
import pandas as pd

import pymysql

import numpy as np

from sqlalchemy import create_engine

#### Second, I will state explicitly the path, connection string and engine that will provide access to our raw data.

In [2]:
sqlitedb_abs_path = '/Users/manuelaquino/Bootcamp/project_m1/data/raw/raw_data_project_m1.db'

connection_string = f'sqlite:///{sqlitedb_abs_path}'

engine = create_engine(connection_string)

#### Down here, I will just see my database tables and query "SELECT *" from each table. 
#### This allows me to confirm my connection and to take a first look at the data contained.

In [3]:
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", engine)

            name
0  personal_info
1   country_info
2    career_info
3      poll_info

In [4]:
pd.read_sql_query("SELECT * FROM personal_info", engine)

,uuid,age,gender,dem_has_children,age_group
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65
...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65

In [5]:
pd.read_sql_query("SELECT * FROM country_info", engine)

                                      uuid country_code        rural
0     f6e7ee00-deac-0133-4de8-0a81e8b09a82           AT  countryside
1     54f0f1c0-dda1-0133-a559-0a81e8b09a82           AT        urban
2     83127080-da3d-0133-c74f-0a81e8b09a82           AT         city
3     15626d40-db13-0133-ea5c-0a81e8b09a82           AT      Country
4     24954a70-db98-0133-4a64-0a81e8b09a82           AT         city
...                                    ...          ...          ...
9644  7d1ac020-dcb4-0133-817a-0a81e8b09a82           SK        urban
9645  39f989f0-db52-0133-8482-0a81e8b09a82           SK        urban
9646  70ce4a90-d965-0133-f5e4-0a81e8b09a82           SK    Non-Rural
9647  2896e440-db3c-0133-5b67-0a81e8b09a82           SK         city
9648  06217ba0-dd56-0133-edda-0a81e8b09a82           SK         city

[9649 rows x 3 columns]

In [6]:
pd.read_sql_query("SELECT * FROM career_info", engine)

,uuid,dem_education_level,dem_full_time_job,normalized_job_code
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,None
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,high,yes,861a9b9151e11362eb3c77ca914172d0
2,83127080-da3d-0133-c74f-0a81e8b09a82,None,no,None
3,15626d40-db13-0133-ea5c-0a81e8b09a82,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c
4,24954a70-db98-0133-4a64-0a81e8b09a82,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f
...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,high,yes,847165cfda6b1dc82ae22b967da8af2f
9645,39f989f0-db52-0133-8482-0a81e8b09a82,high,yes,a4d5b8b38f9513825d0d94a981ebe962
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,low,no,None
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,low,yes,775190277a849cba701b306a7b374c0a
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,high,yes,8a7a3f1bce0958ae9f090683e5a925b7

In [7]:
pd.read_sql_query("SELECT * FROM poll_info", engine)

,uuid,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

#### This step is done to JOIN all tables and start building what will be my first full raw dataframe.

In [8]:
project_m1_full_raw_data = pd.read_sql_query(
"""
SELECT * 
FROM personal_info
JOIN career_info
ON personal_info.uuid = career_info.uuid
JOIN country_info
ON country_info.uuid = career_info.uuid
JOIN poll_info
ON poll_info.uuid = career_info.uuid""", engine)

In [9]:
project_m1_full_raw_data

,uuid,age,gender,dem_has_children,age_group,uuid,dem_education_level,dem_full_time_job,normalized_job_code,uuid,country_code,rural,uuid,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,None,f6e7ee00-deac-0133-4de8-0a81e8b09a82,AT,countryside,f6e7ee00-deac-0133-4de8-0a81e8b09a82,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65,54f0f1c0-dda1-0133-a559-0a81e8b09a82,high,yes,861a9b9151e11362eb3c77ca914172d0,54f0f1c0-dda1-0133-a559-0a81e8b09a82,AT,urban,54f0f1c0-dda1-0133-a559-0a81e8b09a82,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39,83127080-da3d-0133-c74f-0a81e8b09a82,None,no,None,83127080-da3d-0133-c74f-0a81e8b09a82,AT,city,83127080-da3d-0133-c74f-0a81e8b09a82,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65,15626d40-db13-0133-ea5c-0a81e8b09a82,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,15626d40-db13-0133-ea5c-0a81e8b09a82,AT,Country,15626d40-db13-0133-ea5c-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65,24954a70-db98-0133-4a64-0a81e8b09a82,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,24954a70-db98-0133-4a64-0a81e8b09a82,AT,city,24954a70-db98-0133-4a64-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39,7d1ac020-dcb4-0133-817a-0a81e8b09a82,high,yes,847165cfda6b1dc82ae22b967da8af2f,7d1ac020-dcb4-0133-817a-0a81e8b09a82,SK,urban,7d1ac020-dcb4-0133-817a-0a81e8b09a82,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65,39f989f0-db52-0133-8482-0a81e8b09a82,high,yes,a4d5b8b38f9513825d0d94a981ebe962,39f989f0-db52-0133-8482-0a81e8b09a82,SK,urban,39f989f0-db52-0133-8482-0a81e8b09a82,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile,70ce4a90-d965-0133-f5e4-0a81e8b09a82,low,no,None,70ce4a90-d965-0133-f5e4-0a81e8b09a82,SK,Non-Rural,70ce4a90-d965-0133-f5e4-0a81e8b09a82,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65,2896e440-db3c-0133-5b67-0a81e8b09a82,low,yes,775190277a849cba701b306a7b374c0a,2896e440-db3c-0133-5b67-0a81e8b09a82,SK,city,2896e440-db3c-0133-5b67-0a81e8b09a82,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65,06217ba0-dd56-0133-edda-0a81e8b09a82,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,06217ba0-dd56-0133-edda-0a81e8b09a82,SK,city,06217ba0-dd56-0133-edda-0a81e8b09a82,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

In [10]:
type(project_m1_full_raw_data)

pandas.core.frame.DataFrame

#### As we can see, the 'uuid' column used to JOIN is beign repeated.
#### We will try to eliminate the duplicates and keep just one.

In [11]:
project_m1_full_raw_data.columns.unique()

Index(['uuid', 'age', 'gender', 'dem_has_children', 'age_group',
       'dem_education_level', 'dem_full_time_job', 'normalized_job_code',
       'country_code', 'rural', 'question_bbi_2016wave4_basicincome_awareness',
       'question_bbi_2016wave4_basicincome_vote',
       'question_bbi_2016wave4_basicincome_effect',
       'question_bbi_2016wave4_basicincome_argumentsfor',
       'question_bbi_2016wave4_basicincome_argumentsagainst'],
      dtype='object')

In [12]:
project_m1_data = project_m1_full_raw_data[['uuid', 'age', 'gender', 'dem_has_children', 'age_group',
       'dem_education_level', 'dem_full_time_job', 'normalized_job_code',
       'country_code', 'rural', 'question_bbi_2016wave4_basicincome_awareness',
       'question_bbi_2016wave4_basicincome_vote',
       'question_bbi_2016wave4_basicincome_effect',
       'question_bbi_2016wave4_basicincome_argumentsfor',
       'question_bbi_2016wave4_basicincome_argumentsagainst']]

In [13]:
project_m1_data = project_m1_data.loc[:,~project_m1_data.columns.duplicated()]

project_m1_data

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,rural,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65,no,no,None,AT,countryside,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65,high,yes,861a9b9151e11362eb3c77ca914172d0,AT,urban,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39,None,no,None,AT,city,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,AT,Country,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,AT,city,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39,high,yes,847165cfda6b1dc82ae22b967da8af2f,SK,urban,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65,high,yes,a4d5b8b38f9513825d0d94a981ebe962,SK,urban,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile,low,no,None,SK,Non-Rural,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65,low,yes,775190277a849cba701b306a7b374c0a,SK,city,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,SK,city,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

#### The .unique() method allows me to explore the values inside a column to define a cleaning strategy.

In [14]:
project_m1_data['gender'].unique()

array(['male', 'Male', 'Fem', 'FeMale', 'female'], dtype=object)

#### Because there is a low quantity of distinc values, it's easy to identify the ones that need to be corrected and use the .replace() method to clean the inconsistent ones.

In [15]:
project_m1_data['gender'].replace(to_replace = "male", value ="Male", inplace = True)

In [16]:
project_m1_data['gender'].replace(to_replace =["Fem", "FeMale", "female"], value ="Female", inplace = True)

In [17]:
project_m1_data['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [18]:
print(project_m1_data['age'].unique().tolist())

['61 years old', '57 years old', '32 years old', '45 years old', '41 years old', '1990', '47 years old', '34 years old', '1994', '49 years old', '58 years old', '1991', '40 years old', '37 years old', '48 years old', '31 years old', '1999', '1989', '2001', '35 years old', '51 years old', '1988', '42 years old', '33 years old', '64 years old', '38 years old', '55 years old', '1992', '1993', '36 years old', '46 years old', '1998', '44 years old', '1996', '65 years old', '1995', '52 years old', '2002', '50 years old', '1997', '43 years old', '1987', '1986', '39 years old', '53 years old', '62 years old', '2000', '54 years old', '56 years old', '59 years old', '60 years old', '63 years old']

#### For this next step, regex proves useful to eliminate the unwanted part of the strings.

In [19]:
project_m1_cleaned_data = project_m1_data.replace(to_replace=' years old', value='', regex = True)

In [20]:
print(project_m1_cleaned_data['age'].unique())

['61' '57' '32' '45' '41' '1990' '47' '34' '1994' '49' '58' '1991' '40'
 '37' '48' '31' '1999' '1989' '2001' '35' '51' '1988' '42' '33' '64' '38'
 '55' '1992' '1993' '36' '46' '1998' '44' '1996' '65' '1995' '52' '2002'
 '50' '1997' '43' '1987' '1986' '39' '53' '62' '2000' '54' '56' '59' '60'
 '63']

In [21]:
len(project_m1_cleaned_data['age'][5])

4

#### I believe some string values appear to be the "YEAR OF BIRTH". I will substitute them by calculating age by year 2016.

- The number string will need to be converted to interger to support calculation.

In [22]:
project_m1_cleaned_data['age'] = project_m1_cleaned_data['age'].apply(lambda x: 2016 - int(x) if len(x) == 4 else x)

In [23]:
print(project_m1_cleaned_data['age'].unique())

['61' '57' '32' '45' '41' 26 '47' '34' 22 '49' '58' 25 '40' '37' '48' '31'
 17 27 15 '35' '51' 28 '42' '33' '64' '38' '55' 24 23 '36' '46' 18 '44' 20
 '65' 21 '52' 14 '50' 19 '43' 29 30 '39' '53' '62' 16 '54' '56' '59' '60'
 '63']

- I believe it's more convenient to convert this column to type interger/numeric because it will support more numeric operations and provide more information.

In [24]:
project_m1_cleaned_data['age'] = project_m1_cleaned_data['age'].astype(int)

In [25]:
print(project_m1_cleaned_data['age'].unique())

[61 57 32 45 41 26 47 34 22 49 58 25 40 37 48 31 17 27 15 35 51 28 42 33
 64 38 55 24 23 36 46 18 44 20 65 21 52 14 50 19 43 29 30 39 53 62 16 54
 56 59 60 63]

#### There are inconsistencies in the use of uppercase/lowercase size of characters on column ['dem_has_children'].
- Values will be made uppercase for consistency.

In [26]:
project_m1_cleaned_data['dem_has_children'] = project_m1_data['dem_has_children'].str.upper()

In [27]:
project_m1_data['age_group'].unique()

array(['40_65', '26_39', 'juvenile', '14_25'], dtype=object)

#### Looking at the unique values in ['age_group'] we detect one inconsistent one.
- By looking closer to the data I realized that all age values associated to 'juvenile' are inside the '14_25' range and should be placed in this bin.

In [28]:
juvenile = project_m1_cleaned_data[project_m1_cleaned_data['age_group'] == 'juvenile']

juvenile['age'].unique()

array([22, 17, 24, 20, 25, 14, 19, 23, 15, 16, 18, 21])

In [29]:
project_m1_cleaned_data['age_group'] = project_m1_data['age_group'].replace(to_replace = "juvenile", value ="14_25")

project_m1_cleaned_data['age_group'].unique()

array(['40_65', '26_39', '14_25'], dtype=object)

- To make sure values were placed correctly in each bin, I created a filter for each one and doubled checked numbers.

In [30]:
bin_14_25 = project_m1_cleaned_data[project_m1_cleaned_data['age_group'] == '14_25']

bin_26_39 = project_m1_cleaned_data[project_m1_cleaned_data['age_group'] == '26_39']

bin_40_65 = project_m1_cleaned_data[project_m1_cleaned_data['age_group'] == '40_65']

print('bin_14_25 =', bin_14_25['age'].unique())
print('bin_26_39 = ', bin_26_39['age'].unique())
print('bin_40_65 = ', bin_40_65['age'].unique())

bin_14_25 = [22 25 17 15 24 23 18 20 21 14 19 16]
bin_26_39 =  [32 26 34 37 31 27 35 28 33 38 36 29 30 39]
bin_40_65 =  [61 57 45 41 47 49 58 40 48 51 42 64 55 46 44 65 52 50 43 53 62 54 56 59
 60 63]

In [31]:
project_m1_data['dem_full_time_job'].unique()

array(['no', 'yes'], dtype=object)

In [32]:
project_m1_cleaned_data['dem_full_time_job'] = project_m1_data['dem_full_time_job'].str.upper()

#### For the ['rural'] column I think it should be ok to consolidate for only two values: 'urban' or 'rural'.
- rural = rural + countryside + Country
- urban = urban + city + Non-Rural

In [33]:
project_m1_data['rural'].unique()

array(['countryside', 'urban', 'city', 'Country', 'rural', 'Non-Rural'],
      dtype=object)

#### The data shows most of the people live in "urban/city" vs. "rural/countryside", and this is expected.

In [34]:
project_m1_data['rural'].value_counts()

urban          3842
city           1664
rural          1517
Non-Rural      1372
Country         772
countryside     482
Name: rural, dtype: int64

In [35]:
project_m1_data['rural'].replace(to_replace =["countryside", "Country"], value ="rural", inplace = True)
project_m1_data['rural'].replace(to_replace =["city", "Non-Rural"], value ="urban", inplace = True)

In [36]:
project_m1_data['rural'].value_counts()

urban    6878
rural    2771
Name: rural, dtype: int64

In [37]:
project_m1_cleaned_data['rural'] = project_m1_data['rural']

In [38]:
project_m1_cleaned_data['rural'].unique()

array(['rural', 'urban'], dtype=object)

#### I will change the column name from ['rural'] to ['lives in / area type'] because I think its a better description.

In [39]:
project_m1_cleaned_data = project_m1_cleaned_data.rename(columns = {"rural":"lives in / area type"})

In [40]:
project_m1_cleaned_data['lives in / area type'] = project_m1_cleaned_data['lives in / area type'].str.capitalize()

#### Looking at the unique() values inside the ['dem_education_level'] column. I realize we have some nulls/None.
- I checked the total amount of null values to determine if it's better to assume that nulls are probably a "Did not answer / No response" valid option. Or if I should place the nulls/None inside "no education".
- I believe adding 663 null values to "no education" its not necessarily the best way forward to improve data quality.

In [41]:
project_m1_data['dem_education_level'].unique()

array(['no', 'high', None, 'medium', 'low'], dtype=object)

In [42]:
project_m1_data['dem_education_level'].value_counts()

medium    3578
high      3270
low       1815
no         323
Name: dem_education_level, dtype: int64

In [43]:
project_m1_data['dem_education_level'].isnull().value_counts()

False    8986
True      663
Name: dem_education_level, dtype: int64

In [44]:
project_m1_data['dem_education_level'].replace(to_replace ="no", value ="no education", inplace = True)

In [45]:
project_m1_cleaned_data['dem_education_level'] = project_m1_data['dem_education_level']

In [46]:
project_m1_cleaned_data['dem_education_level'].unique()

array(['no education', 'high', None, 'medium', 'low'], dtype=object)

In [47]:
project_m1_cleaned_data[project_m1_data['dem_education_level'].isnull()].head(5)

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,lives in / area type,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
2,83127080-da3d-0133-c74f-0a81e8b09a82,32,Male,NO,26_39,None,NO,None,AT,Urban,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
23,b1eb3870-decd-0133-d783-0a81e8b09a82,25,Female,NO,14_25,None,YES,3833bd699e7afe4665b595f282da0387,AT,Rural,I know something about it,I would vote for it,A basic income would not affect my work choices,It reduces anxiety about financing basic needs...,It might encourage people to stop working
29,12cd5b70-dbd8-0133-0395-0a81e8b09a82,40,Male,YES,40_65,None,YES,dac2e921c1f887d9efc4c06fa33c1397,AT,Rural,I have never heard of it,I would vote for it,‰Û_ work less,None of the above,None of the above
52,c76aa3e0-dbf6-0133-0d62-0a81e8b09a82,49,Male,YES,40_65,None,YES,847165cfda6b1dc82ae22b967da8af2f,AT,Rural,I know something about it,I would probably vote for it,‰Û_ spend more time with my family,It encourages financial independence and self-...,It is impossible to finance
55,d4ac22b0-dd5d-0133-dd11-0a81e8b09a82,46,Female,YES,40_65,None,NO,None,AT,Rural,I know something about it,I would probably vote for it,None of the above,It creates more equality of opportunity | It r...,It might encourage people to stop working | It...

In [48]:
project_m1_cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9649 entries, 0 to 9648
Data columns (total 15 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   uuid                                                 9649 non-null   object
 1   age                                                  9649 non-null   int64
 2   gender                                               9649 non-null   object
 3   dem_has_children                                     9649 non-null   object
 4   age_group                                            9649 non-null   object
 5   dem_education_level                                  8986 non-null   object
 6   dem_full_time_job                                    9649 non-null   object
 7   normalized_job_code                                  5702 non-null   object
 8   country_code                                         9649 non-null   object
 9   lives in / area type                                 9649 non-null   object
 10  question_bbi_2016wave4_basicincome_awareness         9649 non-null   object
 11  question_bbi_2016wave4_basicincome_vote              9649 non-null   object
 12  question_bbi_2016wave4_basicincome_effect            9649 non-null   object
 13  question_bbi_2016wave4_basicincome_argumentsfor      9649 non-null   object
 14  question_bbi_2016wave4_basicincome_argumentsagainst  9649 non-null   object
dtypes: int64(1), object(14)
memory usage: 1.1+ MB

In [49]:
len(project_m1_data['normalized_job_code'].unique())

157

In [50]:
project_m1_cleaned_data['normalized_job_code'].value_counts()

775190277a849cba701b306a7b374c0a    101
d4624ed8068d24948e18303212593cd6     88
dac2e921c1f887d9efc4c06fa33c1397     88
049a3f3a2b5f85cb2971ba77ad66e10c     88
fcaf4aac737e53ad24b9f32f08b8740f     88
                                   ...
58eaf730050d2e23c7361fbb782e30a2      6
5285758deb04c98f58cbae2747195f33      5
7aecc34a90868aac810bf3693b11534e      5
b42566382f2d3deeca56d3667004fc9e      4
631bc3a12ed11340fc94ebfffa8f5f4e      4
Name: normalized_job_code, Length: 156, dtype: int64

In [51]:
project_m1_cleaned_data['question_bbi_2016wave4_basicincome_awareness'].value_counts()

I know something about it              3389
I understand it fully                  2389
I have heard just a little about it    2305
I have never heard of it               1566
Name: question_bbi_2016wave4_basicincome_awareness, dtype: int64

In [52]:
project_m1_cleaned_data['question_bbi_2016wave4_basicincome_vote'].value_counts()

I would probably vote for it        3272
I would vote for it                 2819
I would probably vote against it    1439
I would not vote                    1159
I would vote against it              960
Name: question_bbi_2016wave4_basicincome_vote, dtype: int64

In [53]:
project_m1_cleaned_data['question_bbi_2016wave4_basicincome_effect'].value_counts()

A basic income would not affect my work choices    3349
‰Û_ spend more time with my family                 1387
None of the above                                  1227
‰Û_ gain additional skills                          970
‰Û_ look for a different job                        640
‰Û_ work less                                       629
‰Û_ do more volunteering work                       615
‰Û_ work as a freelancer                            465
‰Û_ stop working                                    367
Name: question_bbi_2016wave4_basicincome_effect, dtype: int64

In [54]:
project_m1_cleaned_data['question_bbi_2016wave4_basicincome_argumentsfor'].value_counts()

None of the above                                                                                                                                                                                                                                                                                                                           2163
It reduces anxiety about financing basic needs                                                                                                                                                                                                                                                                                              1273
It creates more equality of opportunity                                                                                                                                                                                                                                                                                                      848
It encourages financial independence and self-responsibility                                                                                                                                                                                                                                                                                 583
It increases solidarity, because it is funded by everyone                                                                                                                                                                                                                                                                                    479
                                                                                                                                                                                                                                                                                                                                            ...
It increases solidarity, because it is funded by everyone | It increases appreciation for household work and volunteering | It creates more equality of opportunity | It reduces anxiety about financing basic needs | It encourages financial independence and self-responsibility                                                            1
It reduces bureaucracy and administrative expenses | It increases appreciation for household work and volunteering | It encourages financial independence and self-responsibility | It reduces anxiety about financing basic needs | It increases solidarity, because it is funded by everyone                                                 1
It reduces anxiety about financing basic needs | It increases appreciation for household work and volunteering | It increases solidarity, because it is funded by everyone | It creates more equality of opportunity | It encourages financial independence and self-responsibility | It reduces bureaucracy and administrative expenses       1
It reduces bureaucracy and administrative expenses | It increases appreciation for household work and volunteering | It reduces anxiety about financing basic needs | It creates more equality of opportunity | It encourages financial independence and self-responsibility                                                                   1
It reduces bureaucracy and administrative expenses | It encourages financial independence and self-responsibility | It increases solidarity, because it is funded by everyone | It reduces anxiety about financing basic needs | It increases appreciation for household work and volunteering                                                 1
Name: question_bbi_2016wave4_basicincome_argumentsfor, Length: 674, dtype: int64

In [55]:
project_m1_cleaned_data['question_bbi_2016wave4_basicincome_argumentsagainst'].value_counts()

None of the above                                                                                                                                                                                                                                                                                                          1381
Only the people who need it most should get something from the state                                                                                                                                                                                                                                                        875
It might encourage people to stop working                                                                                                                                                                                                                                                                                   823
It is impossible to finance                                                                                                                                                                                                                                                                                                 767
Foreigners might come to my country and take advantage of the benefit                                                                                                                                                                                                                                                       632
                                                                                                                                                                                                                                                                                                                           ...
Only the people who need it most should get something from the state | It is impossible to finance | It is against the principle of linking merit and reward | It might encourage people to stop working | Foreigners might come to my country and take advantage of the benefit | It increases dependence on the state       1
Only the people who need it most should get something from the state | It increases dependence on the state | It is impossible to finance | It might encourage people to stop working | It is against the principle of linking merit and reward                                                                               1
Foreigners might come to my country and take advantage of the benefit | It might encourage people to stop working | It is against the principle of linking merit and reward | It increases dependence on the state | It is impossible to finance | Only the people who need it most should get something from the state       1
It is against the principle of linking merit and reward | It might encourage people to stop working | Only the people who need it most should get something from the state | It increases dependence on the state | Foreigners might come to my country and take advantage of the benefit | It is impossible to finance       1
It is impossible to finance | Foreigners might come to my country and take advantage of the benefit | It might encourage people to stop working | It increases dependence on the state | It is against the principle of linking merit and reward | Only the people who need it most should get something from the state       1
Name: question_bbi_2016wave4_basicincome_argumentsagainst, Length: 881, dtype: int64

In [56]:
import requests

response = requests.get('http://api.dataatwork.org/v1/jobs?limit=500')

json_data = response.json()

len(json_data)

501

In [57]:
json_data[0:5]

[{'uuid': '26bc4486dfd0f60b3bb0d8d64e001800',
  'title': '1st Grade Teacher',
  'normalized_job_title': '1st grade teacher',
  'parent_uuid': '51cc95467c1844c7dc1d923265c023b2'},
 {'uuid': '9be6e14491305132c175cb1781a3356c',
  'title': '1st Pressman',
  'normalized_job_title': '1st pressman',
  'parent_uuid': '96f1cf15fe5880d8660c70f0756944ab'},
 {'uuid': 'd38d16bab3f9f25ae34ae3e2aad254d4',
  'title': '1st Pressman On Web Press',
  'normalized_job_title': '1st pressman on web press',
  'parent_uuid': '96f1cf15fe5880d8660c70f0756944ab'},
 {'uuid': '8576a78b5c1cae3a567ca7fd34500357',
  'title': '21 Dealer',
  'normalized_job_title': '21 dealer',
  'parent_uuid': '4be080220c824dcb435d59ebf1c3ce80'},
 {'uuid': 'a59278d7f653db37e54a270345a91a05',
  'title': '2nd Grade Teacher',
  'normalized_job_title': '2nd grade teacher',
  'parent_uuid': '51cc95467c1844c7dc1d923265c023b2'}]

In [58]:
dataatwork_api_response = requests.get('http://api.dataatwork.org/v1/jobs/861a9b9151e11362eb3c77ca914172d0')

In [59]:
dataatwork_api_response

In [60]:
json_dataatwork_api_response = dataatwork_api_response.json()

In [61]:
json_dataatwork_api_response

{'uuid': '861a9b9151e11362eb3c77ca914172d0',
 'title': 'Automatic Data Processing Planner',
 'normalized_job_title': 'automatic data processing planner',
 'parent_uuid': '0148f61d4227497728ce33490843d056'}

In [62]:
json_dataatwork_api_response['title']

'Automatic Data Processing Planner'

In [63]:
unique_job_codes_in_db = project_m1_cleaned_data['normalized_job_code'].unique()

In [64]:
unique_job_codes_in_db[0:5]

array([None, '861a9b9151e11362eb3c77ca914172d0',
       '049a3f3a2b5f85cb2971ba77ad66e10c',
       'f4b2fb1aa40f661488e2782b6d57ad2f',
       '27af8700f5577cec835acee2cb90a2ff'], dtype=object)

In [65]:
unique_job_code_list = list(unique_job_codes_in_db[1:])

In [66]:
unique_job_code_list[0:10]

['861a9b9151e11362eb3c77ca914172d0',
 '049a3f3a2b5f85cb2971ba77ad66e10c',
 'f4b2fb1aa40f661488e2782b6d57ad2f',
 '27af8700f5577cec835acee2cb90a2ff',
 'c1b670eba9ccb65e7c99f7da116d5b9c',
 'd71c4164c99a5f9bca773e755a72f40f',
 '2ee80cf30e2483dfe0947adc0428f8c5',
 '897ef18a9321616495831a4b4b0c1bb2',
 'a003702c0cea282e17967772dd83de5e',
 '04c82eae29e1c4a30eac0710b74ab276']

In [67]:
for job_code in unique_job_code_list[0:5]:
    job_code_response = requests.get(f'http://api.dataatwork.org/v1/jobs/{job_code}').json()
    print(job_code_response)

{'uuid': '861a9b9151e11362eb3c77ca914172d0', 'title': 'Automatic Data Processing Planner', 'normalized_job_title': 'automatic data processing planner', 'parent_uuid': '0148f61d4227497728ce33490843d056'}
{'uuid': '049a3f3a2b5f85cb2971ba77ad66e10c', 'title': 'Data Coordinator', 'normalized_job_title': 'data coordinator', 'parent_uuid': '0b9dd32a367f4562ec77b993053d1910'}
{'uuid': 'f4b2fb1aa40f661488e2782b6d57ad2f', 'title': 'Database Developer', 'normalized_job_title': 'database developer', 'parent_uuid': 'b90ca4df5690002377a7b0f1f3d40781'}
{'uuid': '27af8700f5577cec835acee2cb90a2ff', 'title': 'Data Entry Specialist', 'normalized_job_title': 'data entry specialist', 'parent_uuid': 'bf88358c56bb6cbe7eabec38ae333d19'}
{'uuid': 'c1b670eba9ccb65e7c99f7da116d5b9c', 'title': 'Database Architect', 'normalized_job_title': 'database architect', 'parent_uuid': '596226d5f9ef63de41a852826d483d19'}

In [68]:
for job_code in unique_job_code_list:
    job_code_response = requests.get(f'http://api.dataatwork.org/v1/jobs/{job_code}').json()
    print(job_code_response)
    print(job_code_response['uuid'])
    print(job_code_response['title'])
    break

{'uuid': '861a9b9151e11362eb3c77ca914172d0', 'title': 'Automatic Data Processing Planner', 'normalized_job_title': 'automatic data processing planner', 'parent_uuid': '0148f61d4227497728ce33490843d056'}
861a9b9151e11362eb3c77ca914172d0
Automatic Data Processing Planner

In [69]:
job_code_dict = {}

for job_code in unique_job_code_list:
    job_code_response = requests.get(f'http://api.dataatwork.org/v1/jobs/{job_code}').json()
    job_code_dict[job_code] = job_code_response['title']

job_code_dict

{'861a9b9151e11362eb3c77ca914172d0': 'Automatic Data Processing Planner',
 '049a3f3a2b5f85cb2971ba77ad66e10c': 'Data Coordinator',
 'f4b2fb1aa40f661488e2782b6d57ad2f': 'Database Developer',
 '27af8700f5577cec835acee2cb90a2ff': 'Data Entry Specialist',
 'c1b670eba9ccb65e7c99f7da116d5b9c': 'Database Architect',
 'd71c4164c99a5f9bca773e755a72f40f': 'Geographic Information Systems Database Administrator (GIS Database Administrator)',
 '2ee80cf30e2483dfe0947adc0428f8c5': 'Crime Data Specialist',
 '897ef18a9321616495831a4b4b0c1bb2': 'Data Communications Software Consultant',
 'a003702c0cea282e17967772dd83de5e': 'Data Security Analyst',
 '04c82eae29e1c4a30eac0710b74ab276': 'Database Marketing Analyst',
 'fcaf4aac737e53ad24b9f32f08b8740f': 'Computer or Data Processing Systems Consultant',
 '3833bd699e7afe4665b595f282da0387': 'Database Development and Administration Project Manager',
 '19e384e977796c25780d8c28b12089c4': 'Naval Tactical Data System--Combat Information Center Watch Officer, General',
 '474b962c13632a04e42a546be4f11dbb': 'Data Coder Operator',
 'dac2e921c1f887d9efc4c06fa33c1397': 'Automatic Data Processing Customer Liaison (ADP Customer Liaison)',
 '996da29c84f5eed00da40c230f4c4078': 'Data Entry Representative',
 'cc2b26cc436bea36bda3bdd7367c411a': 'Data Processing Auditor',
 '25fe195cbf915c0824fa6c44e6d0008c': 'Maintenance Data Analyst',
 '76385cb24e831b3364279b9de5641d8f': 'Automatic Data Processing Systems Security Specialist (ADP Systems Security)',
 '16b67d7f57698455aefbc1ae1b358b50': 'Database Engineer',
 'b24ece3300d2f8ab34f9553e531183d6': 'Data Processing Systems Project Planner',
 '5db2c8d6539f983e1ca3d7c5b939e190': 'Database Administration Associate',
 '36675c937946c8a4fc5de7d0b4c850de': 'Data Warehousing Engineer',
 '847165cfda6b1dc82ae22b967da8af2f': 'Data Warehouse Developer',
 '2ca138b991c50dc6696238e5ad800142': 'Database Software Technician',
 '775190277a849cba701b306a7b374c0a': 'Data Officer',
 '022d0e3a40aa3e29bca6851542b27842': 'Data Keyer',
 '375017ea3a1a97f5ea676def873bb25b': 'Geographic Information Systems Data Specialist (GIS Data Specialist)',
 '1dd2fdc8a3981f2a1d8f0ca173952bb8': 'Database Administration Manager',
 'e605336f5a43949cb6b18054fd1937f1': 'Database Security Expert',
 '800b621aab5dac18f4caef621fa43a49': 'Data Systems Manager',
 'd06dfb43c95b585a89ae556c9221b573': 'Data Warehousing Manager',
 'a12a16280e22220f9354333f6fe1b22a': 'Geographic Information Systems Data Administrator (GIS Data Administrator)',
 '477b53ef09d37f098d5ed74f47fcbaec': 'Data Base Design Analyst',
 'e2f68bf748aea2c7d2254550c0c92b23': 'Director of Data Operations',
 '45033f83b6e0309eca9bcd76917f15d0': 'Database Modeler',
 '141ddda0f613da65a280521247de0e9f': 'Data Administrator',
 '3ddea1b52e520996e4ec9fb70dc8b86b': 'Field Artillery Automated Tactical Data System Specialist',
 '6408c0d7c7faa4ced47fbc8474698126': 'Database Design Analyst',
 '07b7555fa790debaf5b04d1409ad5f11': 'Database Security Administrator',
 'a4d5b8b38f9513825d0d94a981ebe962': 'Database Manager',
 '5e93fd1a58c8a67b295f69d87d1a940d': 'Geographic Information Systems Data Manager (GIS Data Manager)',
 '122f24bc911a79c26ca66210557dda07': 'Clinical Data Specialist',
 '76b0ba6af40991629e20dff36edd02a5': 'Data Management Information Technology Specialist',
 '970eb38c7b3eb080466052ea994af189': 'Internet Database Specialist',
 'cf2d4db3c258faa2499bdeeeed6721a5': 'GPS Field Data Collector (Global Positioning System Field Data Collector)',
 '90c5430dbc810aec8695af2f1f4c42e8': 'Electronic Data Processing Auditor (EDP Auditor)',
 '7bb15eefb19ed09c59349baad7e8469e': 'Database Coordinator',
 'ec3d88b2fd083b870b8c5a603898ed39': 'Databases Computer Consultant',
 '1f8576bdffa64f492405d02b842c41a6': 'Data Management Associate',
 'edc64316da9707432443c7a4461abe6c': 'Data Security Administrator',
 '6cf4d336112984368f83181ac5ffe948': 'Health Data Analyst',
 'd4624ed8068d24948e18303212593cd6': 'Data Architect',
 '1a281bf4bd1fe9b2a6e464e508bea167': 'Data Storage Specialist',
 '2f704538f6c9d6459a97314be98124e2': 'Data Collector',
 '3161063d378eecc4581c5cdee46a2a6c': 'Head of Information Systems and Data Processing',
 '781f5d3a80812531fdc81125a527a626': 'Data Warehouse Specialist',
 '38a15ceadcdd6d4db16a88fa1a72b083': 'Data Warehouse Analyst',
 'e55556364d2096578fd153e9800e826f': 'Database Consultant',
 'd24ffac92c24fb0e7bd1abc5fc3b6254': 'Data Manager',
 'ccd7528fb38f16077360c5b67c9700c4': 'Data Communications Analyst',
 'f6fbd9dea1fa8f899683ade8e7d87d60': 'Data Entry Associate',
 '0de6170ccbed08e62b2e5862d5846a43': 'Database Tester',
 '499f9d9b6722342608656559b15abd90': 'Clinical Data Associate',
 '8a7a3f1bce0958ae9f090683e5a925b7': 'Data Scientist',
 '7acaed29536648e45ea2b82d45047fcf': 'Medical Data Analyst',
 '02e4c028f64f176de2f54bbc2f5403ce': 'Marketing Database Analyst',
 '569da68cdcac43a3b4a0126ea9170570': 'Database Designer',
 'ced804d972b03cca6d523ec8925a7943': 'Oracle Database Administrator (Oracle DBA)',
 '41b2978a2c07c5f477e60f26372d6c85': 'Database Management System Specialist (DBMS Specialist)',
 'd9e964a222fdd9527319ad88adbfaa2e': 'SQL Database Administrator',
 'ac47656fd51c2cd8037057262c910dc4': 'Data Processing Manager',
 'e49986dae76619a3941d280ee14d38ae': 'Data Miner',
 'f842344417ed2fc226d9cc00f9562458': 'Log Data Technician',
 '096536ec43ce2a7de73031b271a1c132': 'Flight Data Technician',
 'a33662485eb4ad97096183db945308f4': 'Automatic Data Processing Planner (ADP Planner)',
 '4f75f97ac5b5f00f9420074d501f0803': 'Data Capture Specialist',
 'f36c6ada3a808453a0bf241c74a4e994': 'Reference Data Expert',
 '41ba88cfd476ee8d5e3d9f7cea62f051': 'Data Recovery Planner',
 '894ca61c22718617c7e2404f582153da': 'Data Processing Consultant',
 '34d80517fe3bc143f9fc850386b8ffd7': 'Clinical Data Coordinator',
 'e7b3e1c6a32c7247cd4857e4c3574165': 'Data Processing Systems Analyst',
 '36ac256201657eeaa67ee95aaae3cd54': 'Data Warehousing Specialist',
 'bc6dcc49557388a9f53d6e642e73d7a2': 'Business Database Analyst',
 '00bff17fca67555d8d86e8ead86dcd70': 'Database Analyst',
 'b42566382f2d3deeca56d3667004fc9e': 'Data Center Manager',
 '7932d4705d002b47789c11edfaed685e': 'Data Control Assistant',
 'aee597cd78f235c9db9d3ca987c7c846': 'Database Development Project Manager',
 '1c37a6e2bf157c0eff4665c57c52602d': 'SCADA Technician (Supervisory Control and Data Acquisition Technician)',
 '46b09f5f86f1ed46a8cb8e14d41418c7': 'Survey Data Technician',
 'a2a9fbe67b4aa2b551ba0f3adac90a99': 'Engineer, System Electronic Data Processing (Engineer, System EDP)',
 '77d124811ae6887bd4ff42b0e2b49116': 'Data Warehouse Architect',
 'f05d2014d4a9adaab50fa1e0ca6f6c8c': 'Naval Tactical Data System--Combat Information Center Watch Officer, Carrier Controlled Approach Controller',
 'ac2588d5d7676a49bdcd038e4a0a0ec5': 'Data Compiler',
 '2173ff3afd8d28192f7cf119af201940': 'Data Modeling Specialist',
 'f5bc91b67dc30ad204158092116c4ed2': 'Clinical Data Manager',
 '433df1b945d32f17d9e61cf60a9bd06e': 'Data Abstractor',
 '1295a187473fd2f53427769fc7a4c02e': 'Clinical Data Management Associate Director',
 '004431b0c1ce29ff6145307fa23f3f98': 'Data Reduction Technician',
 '8fd068c8d9be73abfa678856177b6c40': 'Data Operations Director',
 'c34f03aa0a9c6edbe8ec50f4fa3687a8': 'Data Center Operator',
 '7aecc34a90868aac810bf3693b11534e': 'Clinical Trials Data Coordinator',
 '086f0063610283d1c23c44bca4ef92c0': 'Database Administrator (DBA)',
 '16b49a63ac3fcb90356c30187110ed94': 'Data Processing Auxiliary Equipment Operator',
 '437e4414c78611a270a5cedb4b4c0eed': 'Data Collection Technician',
 '679fb7003e0aedc14891fcd15dd846c5': 'Database Specialist',
 '7a37ddb38441873334fd8ff07c17ad22': 'Data Acquisition Technician',
 '58eaf730050d2e23c7361fbb782e30a2': 'Data Processing Mechanic',
 'd0abc47e83e7d85921e113f85175547a': 'Data Sciences Director',
 '73d251075a710326ae436d9819246377': 'Databases Software Consultant',
 '5e2bfe1fb8451158ff488c673535980c': 'Data Entry Machine Operator',
 'ac9f868b5c3e7cb3f31bcead5dadeb71': 'Micro Computer Data Processor',
 'f670246beda8187fbe875401e7bc4ba6': 'Data Processing Services Sales Representative',
 '0044971fda4a261b6049a63817913e95': 'Data Processing Equipment Repairer',
 'b36bc5f02fd641a126df999bcefa2777': 'Data Technician',
 '067c85859a63aa6f1c8c936904124dd6': 'Naval Tactical Data System--Combat Information Center Officer',
 '491d82be40d8395e347f9584124bccdd': 'Flight Test Data Acquisition Technician',
 '7028f15ad274cb4d9505101b9c1306b1': 'Clinical Data Management Manager (CDM Manager)',
 'fd69391dc29c83d5ad744daa57de0175': 'Data Transcriber',
 '3def30a9bc4356164176ba909f40bab8': 'Data Input Clerk',
 '132aa9e82c5d4c8a395342d0a6e22c5c': 'Electronic Data Interchange System Developer (EDI System Developer)',
 '07b2ace822aff5d35dcf5ea264ef3b59': 'Database Administration Project Manager',
 'f8984e50675cf61e5ac1ea8f661e0ab2': 'Field Traffic Data Technician',
 'd329d187dafb7546061ec7fbf137a2b4': 'Clinical Data Abstractor',
 'd63e35f948115e0c328a49db7bdb6e59': 'Data Control Clerk Supervisor',
 'bf7f43295d45cdced048c8126f977b6b': 'Datastage Developer',
 '6bf4290b983d58ce153af610008846c9': 'Data Entry Technician',
 'f1fc61f279e3ad14863e582ca6fdc473': 'Clinical Data Analyst',
 '31bf3181813e21ffdfd76b5881fab066': 'Data Entry Supervisor',
 '04b0eaf624b2deb45ccd62cf6ec7c7bc': 'Data Conversion Operator',
 '2616d64becb4f2c478dd42f501bbfbff': 'Data Processing Control Clerk',
 '776bf47111206d31ccf835650e1054cc': 'Data Typist',
 'c3b5ebd7b88c20786f11e87846c7d6ae': 'SCADA Operator (Supervisory Control and Data Acquisition Operator)',
 'dfea9e8bc3c565ff9e64d4288b1c423d': 'Customer Data Technician',
 'a50d1f4be063829950e6ddb02c91379f': 'Database Programmer',
 'af6630abd24c19f77cfba94aa4e3b7e1': 'Data Specialist',
 '901740e84d1a4760e440b039adac9df2': 'Data Processing Clerk',
 'f2ecf36d7eb0a4225974fc6c4f48cfcb': 'Voice and Data Technician',
 'f1fb62e4c97f4f5cd5001877cb94379e': 'Data Processor',
 'b9a57264eaada670703db113483ddfc3': 'Data Modeler',
 '65b92572bca68ff9c49c930749fa348c': 'LiDAR Data Analyst',
 '59dab7d0a3ee97d939aa8b1a8deec857': 'Data Management Manager',
 'afea0e0169a98ee264db2ddb1c6e6a34': 'Data Processing Supervisor',
 '0facaffe51cc1998a5fbdbe5fd18fd98': 'Weight in Motion Field Data Collection Technician',
 'ccf2c4daae069f054cada4c911819a17': 'Scientific Database Curator',
 '1426c924e1b6b162f6bfdd1906d98d0e': 'Operations Officer, Afloat (Naval Tactical Data Systems)',
 'eb3d789747d52df803ce63fe37bf53e9': 'Data Analyst',
 'bdf4dcd92089bc17345de83f4d06090f': 'Data Entry Operator',
 '5285758deb04c98f58cbae2747195f33': 'Data Reviewer',
 '04c27c76b463a917800549cf88a59961': 'Data Communications Technician',
 '631bc3a12ed11340fc94ebfffa8f5f4e': 'Database Technician',
 'b0fa6ede410f50b82ab74f5a705fe699': 'Analytical Data Miner',
 '559a21f836c93876f31b60e6d10656a7': 'Data Analysis Assistant',
 'c1fb1a01b78373ac2153c66fa08d16dc': 'Data Examination Clerk',
 '05bb9a333a66d6eb151e253623efe1c0': 'Data Entry Clerk',
 '4cee16550636e292b8d136486fce943b': 'Data Capture Clerk'}

In [70]:
job_code_df = pd.DataFrame.from_dict(job_code_dict, orient='index', columns=['job_description'])

job_code_df

                                                    job_description
861a9b9151e11362eb3c77ca914172d0  Automatic Data Processing Planner
049a3f3a2b5f85cb2971ba77ad66e10c                   Data Coordinator
f4b2fb1aa40f661488e2782b6d57ad2f                 Database Developer
27af8700f5577cec835acee2cb90a2ff              Data Entry Specialist
c1b670eba9ccb65e7c99f7da116d5b9c                 Database Architect
...                                                             ...
b0fa6ede410f50b82ab74f5a705fe699              Analytical Data Miner
559a21f836c93876f31b60e6d10656a7            Data Analysis Assistant
c1fb1a01b78373ac2153c66fa08d16dc             Data Examination Clerk
05bb9a333a66d6eb151e253623efe1c0                   Data Entry Clerk
4cee16550636e292b8d136486fce943b                 Data Capture Clerk

[156 rows x 1 columns]

In [71]:
job_code_df.columns

Index(['job_description'], dtype='object')

In [72]:
job_code_df.index

Index(['861a9b9151e11362eb3c77ca914172d0', '049a3f3a2b5f85cb2971ba77ad66e10c',
       'f4b2fb1aa40f661488e2782b6d57ad2f', '27af8700f5577cec835acee2cb90a2ff',
       'c1b670eba9ccb65e7c99f7da116d5b9c', 'd71c4164c99a5f9bca773e755a72f40f',
       '2ee80cf30e2483dfe0947adc0428f8c5', '897ef18a9321616495831a4b4b0c1bb2',
       'a003702c0cea282e17967772dd83de5e', '04c82eae29e1c4a30eac0710b74ab276',
       ...
       'eb3d789747d52df803ce63fe37bf53e9', 'bdf4dcd92089bc17345de83f4d06090f',
       '5285758deb04c98f58cbae2747195f33', '04c27c76b463a917800549cf88a59961',
       '631bc3a12ed11340fc94ebfffa8f5f4e', 'b0fa6ede410f50b82ab74f5a705fe699',
       '559a21f836c93876f31b60e6d10656a7', 'c1fb1a01b78373ac2153c66fa08d16dc',
       '05bb9a333a66d6eb151e253623efe1c0', '4cee16550636e292b8d136486fce943b'],
      dtype='object', length=156)

In [73]:
job_code_df = job_code_df.reset_index()

In [74]:
job_code_df.columns

Index(['index', 'job_description'], dtype='object')

In [75]:
job_code_df.index

RangeIndex(start=0, stop=156, step=1)

In [76]:
job_code_df

                                index                    job_description
0    861a9b9151e11362eb3c77ca914172d0  Automatic Data Processing Planner
1    049a3f3a2b5f85cb2971ba77ad66e10c                   Data Coordinator
2    f4b2fb1aa40f661488e2782b6d57ad2f                 Database Developer
3    27af8700f5577cec835acee2cb90a2ff              Data Entry Specialist
4    c1b670eba9ccb65e7c99f7da116d5b9c                 Database Architect
..                                ...                                ...
151  b0fa6ede410f50b82ab74f5a705fe699              Analytical Data Miner
152  559a21f836c93876f31b60e6d10656a7            Data Analysis Assistant
153  c1fb1a01b78373ac2153c66fa08d16dc             Data Examination Clerk
154  05bb9a333a66d6eb151e253623efe1c0                   Data Entry Clerk
155  4cee16550636e292b8d136486fce943b                 Data Capture Clerk

[156 rows x 2 columns]

In [77]:
job_code_df = job_code_df.rename(columns = {"index":"job_code"})

job_code_df

                             job_code                    job_description
0    861a9b9151e11362eb3c77ca914172d0  Automatic Data Processing Planner
1    049a3f3a2b5f85cb2971ba77ad66e10c                   Data Coordinator
2    f4b2fb1aa40f661488e2782b6d57ad2f                 Database Developer
3    27af8700f5577cec835acee2cb90a2ff              Data Entry Specialist
4    c1b670eba9ccb65e7c99f7da116d5b9c                 Database Architect
..                                ...                                ...
151  b0fa6ede410f50b82ab74f5a705fe699              Analytical Data Miner
152  559a21f836c93876f31b60e6d10656a7            Data Analysis Assistant
153  c1fb1a01b78373ac2153c66fa08d16dc             Data Examination Clerk
154  05bb9a333a66d6eb151e253623efe1c0                   Data Entry Clerk
155  4cee16550636e292b8d136486fce943b                 Data Capture Clerk

[156 rows x 2 columns]

In [78]:
project_m1_cleaned_data

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,lives in / area type,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61,Male,NO,40_65,no education,NO,None,AT,Rural,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57,Male,YES,40_65,high,YES,861a9b9151e11362eb3c77ca914172d0,AT,Urban,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32,Male,NO,26_39,None,NO,None,AT,Urban,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45,Male,YES,40_65,high,YES,049a3f3a2b5f85cb2971ba77ad66e10c,AT,Rural,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41,Female,YES,40_65,high,YES,f4b2fb1aa40f661488e2782b6d57ad2f,AT,Urban,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37,Female,NO,26_39,high,YES,847165cfda6b1dc82ae22b967da8af2f,SK,Urban,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53,Male,YES,40_65,high,YES,a4d5b8b38f9513825d0d94a981ebe962,SK,Urban,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,24,Male,NO,14_25,low,NO,None,SK,Urban,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47,Male,YES,40_65,low,YES,775190277a849cba701b306a7b374c0a,SK,Urban,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51,Female,YES,40_65,high,YES,8a7a3f1bce0958ae9f090683e5a925b7,SK,Urban,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

In [79]:
project_m1_cleaned_data = pd.merge(project_m1_cleaned_data, job_code_df, 'left', left_on=['normalized_job_code'], right_on=['job_code'])

project_m1_cleaned_data

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,lives in / area type,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst,job_code,job_description
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61,Male,NO,40_65,no education,NO,None,AT,Rural,I know something about it,I would not vote,None of the above,None of the above,None of the above,NaN,NaN
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57,Male,YES,40_65,high,YES,861a9b9151e11362eb3c77ca914172d0,AT,Urban,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working,861a9b9151e11362eb3c77ca914172d0,Automatic Data Processing Planner
2,83127080-da3d-0133-c74f-0a81e8b09a82,32,Male,NO,26_39,None,NO,None,AT,Urban,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...,NaN,NaN
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45,Male,YES,40_65,high,YES,049a3f3a2b5f85cb2971ba77ad66e10c,AT,Rural,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above,049a3f3a2b5f85cb2971ba77ad66e10c,Data Coordinator
4,24954a70-db98-0133-4a64-0a81e8b09a82,41,Female,YES,40_65,high,YES,f4b2fb1aa40f661488e2782b6d57ad2f,AT,Urban,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...,f4b2fb1aa40f661488e2782b6d57ad2f,Database Developer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37,Female,NO,26_39,high,YES,847165cfda6b1dc82ae22b967da8af2f,SK,Urban,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance,847165cfda6b1dc82ae22b967da8af2f,Data Warehouse Developer
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53,Male,YES,40_65,high,YES,a4d5b8b38f9513825d0d94a981ebe962,SK,Urban,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...,a4d5b8b38f9513825d0d94a981ebe962,Database Manager
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,24,Male,NO,14_25,low,NO,None,SK,Urban,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above,NaN,NaN
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47,Male,YES,40_65,low,YES,775190277a849cba701b306a7b374c0a,SK,Urban,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...,775190277a849cba701b306a7b374c0a,Data Officer
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51,Female,YES,40_65,high,YES,8a7a3f1bce0958ae9f090683e5a925b7,SK,Urban,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...,8a7a3f1bce0958ae9f090683e5a925b7,Data Scientist

In [80]:
project_m1_cleaned_data = project_m1_cleaned_data.drop(columns=['job_code'])

project_m1_cleaned_data

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,lives in / area type,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst,job_description
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61,Male,NO,40_65,no education,NO,None,AT,Rural,I know something about it,I would not vote,None of the above,None of the above,None of the above,NaN
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57,Male,YES,40_65,high,YES,861a9b9151e11362eb3c77ca914172d0,AT,Urban,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working,Automatic Data Processing Planner
2,83127080-da3d-0133-c74f-0a81e8b09a82,32,Male,NO,26_39,None,NO,None,AT,Urban,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...,NaN
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45,Male,YES,40_65,high,YES,049a3f3a2b5f85cb2971ba77ad66e10c,AT,Rural,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above,Data Coordinator
4,24954a70-db98-0133-4a64-0a81e8b09a82,41,Female,YES,40_65,high,YES,f4b2fb1aa40f661488e2782b6d57ad2f,AT,Urban,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...,Database Developer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37,Female,NO,26_39,high,YES,847165cfda6b1dc82ae22b967da8af2f,SK,Urban,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance,Data Warehouse Developer
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53,Male,YES,40_65,high,YES,a4d5b8b38f9513825d0d94a981ebe962,SK,Urban,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...,Database Manager
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,24,Male,NO,14_25,low,NO,None,SK,Urban,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above,NaN
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47,Male,YES,40_65,low,YES,775190277a849cba701b306a7b374c0a,SK,Urban,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...,Data Officer
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51,Female,YES,40_65,high,YES,8a7a3f1bce0958ae9f090683e5a925b7,SK,Urban,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...,Data Scientist

In [81]:
project_m1_cleaned_data['job_description'] = project_m1_cleaned_data['job_description'].fillna('Unknown')

project_m1_cleaned_data

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,lives in / area type,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst,job_description
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61,Male,NO,40_65,no education,NO,None,AT,Rural,I know something about it,I would not vote,None of the above,None of the above,None of the above,Unknown
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57,Male,YES,40_65,high,YES,861a9b9151e11362eb3c77ca914172d0,AT,Urban,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working,Automatic Data Processing Planner
2,83127080-da3d-0133-c74f-0a81e8b09a82,32,Male,NO,26_39,None,NO,None,AT,Urban,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...,Unknown
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45,Male,YES,40_65,high,YES,049a3f3a2b5f85cb2971ba77ad66e10c,AT,Rural,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above,Data Coordinator
4,24954a70-db98-0133-4a64-0a81e8b09a82,41,Female,YES,40_65,high,YES,f4b2fb1aa40f661488e2782b6d57ad2f,AT,Urban,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...,Database Developer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37,Female,NO,26_39,high,YES,847165cfda6b1dc82ae22b967da8af2f,SK,Urban,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance,Data Warehouse Developer
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53,Male,YES,40_65,high,YES,a4d5b8b38f9513825d0d94a981ebe962,SK,Urban,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...,Database Manager
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,24,Male,NO,14_25,low,NO,None,SK,Urban,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above,Unknown
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47,Male,YES,40_65,low,YES,775190277a849cba701b306a7b374c0a,SK,Urban,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...,Data Officer
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51,Female,YES,40_65,high,YES,8a7a3f1bce0958ae9f090683e5a925b7,SK,Urban,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...,Data Scientist

In [82]:
print(list(project_m1_cleaned_data['country_code'].unique()))

['AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'MT', 'NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK']

In [83]:
len(list(project_m1_cleaned_data['country_code'].unique()))

28

In [84]:
import requests

url = 'https://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Country_codes'
html = requests.get(url).content
html[:2000]

b'\xef\xbb\xbf<!DOCTYPE html>\n<html lang="en" dir="ltr" class="client-nojs">\n<head>\n<meta http-equiv="X-UA-Compatible" content="Ie=Edge,chrome=1"/> <meta charset="UTF-8" /><title>Glossary:Country codes - Statistics Explained</title>\n<meta name="generator" content="MediaWiki 1.22.5" />\n<link rel="shortcut icon" href="https://ec.europa.eu/eurostat/estat-theme/images/favicon.ico" />\n<link rel="search" type="application/opensearchdescription+xml" href="/eurostat/statistics-explained/opensearch_desc.php" title="Statistics Explained (en)" />\n<link rel="EditURI" type="application/rsd+xml" href="https://ec.europa.eu/eurostat/statistics-explained/api.php?action=rsd" />\n<link rel="alternate" type="application/atom+xml" title="Statistics Explained Atom feed" href="/eurostat/statistics-explained/index.php?title=Special:RecentChanges&amp;feed=atom" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=ext.rtlcite&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.shared&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=skins.statexpflat&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<meta name="ResourceLoaderDynamicStyles" content="" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=site&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<style>a:lang(ar), a:lang(ckb), a:lang(kk-arab), a:lang(mzn), a:lang(ps), a:lang(ur) { text-decoration: none; }</style>\n\n<script src="https://ec.europa.eu/eurosta'

In [85]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, 'html.parser')

soup

<!DOCTYPE html>

<html class="client-nojs" dir="ltr" lang="en">
<head>
<meta content="Ie=Edge,chrome=1" http-equiv="X-UA-Compatible"/> <meta charset="utf-8"/><title>Glossary:Country codes - Statistics Explained</title>
<meta content="MediaWiki 1.22.5" name="generator"/>
<link href="https://ec.europa.eu/eurostat/estat-theme/images/favicon.ico" rel="shortcut icon"/>
<link href="/eurostat/statistics-explained/opensearch_desc.php" rel="search" title="Statistics Explained (en)" type="application/opensearchdescription+xml"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="/eurostat/statistics-explained/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Statistics Explained Atom feed" type="application/atom+xml"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=ext.rtlcite&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.shared&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=skins.statexpflat&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=site&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<style>a:lang(ar), a:lang(ckb), a:lang(kk-arab), a:lang(mzn), a:lang(ps), a:lang(ur) { text-decoration: none; }</style>
<script src="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=statexpflat&amp;*"></script>
<script>if(window.mw){
mw.config.set( {
    "wgCanonicalNamespace": "Glossary",
    "wgCanonicalSpecialPageName": false,
    "wgNamespaceNumber": 100,
    "wgPageName": "Glossary:Country_codes",
    "wgTitle": "Country codes",
    "wgCurRevisionId": 512615,
    "wgRevisionId": 512615,
    "wgArticleId": 1994,
    "wgIsArticle": true,
    "wgIsRedirect": false,
    "wgAction": "view",
    "wgUserName": null,
    "wgUserGroups": [
        "*"
    ],
    "wgCategories": [
        "Geography glossary",
        "Glossary"
    ],
    "wgBreakFrames": false,
    "wgPageContentLanguage": "en",
    "wgPageContentModel": "wikitext",
    "wgSeparatorTransformTable": [
        "",
        ""
    ],
    "wgDigitTransformTable": [
        "",
        ""
    ],
    "wgDefaultDateFormat": "dmy",
    "wgMonthNames": [
        "",
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ],
    "wgMonthNamesShort": [
        "",
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec"
    ],
    "wgRelevantPageName": "Glossary:Country_codes",
    "wgIsProbablyEditable": false,
    "wgRestrictionEdit": [],
    "wgRestrictionMove": [],
    "wgWikiEditorEnabledModules": {
        "toolbar": true,
        "dialogs": false,
        "hidesig": true,
        "templateEditor": false,
        "templates": false,
        "preview": false,
        "previewDialog": false,
        "publish": false,
        "toc": false
    },
    "wgCategoryTreePageCategoryOptions": "{\"mode\":0,\"hideprefix\":20,\"showcount\":true,\"namespaces\":false}"
} );
}</script><script>if(window.mw){
mw.loader.implement( "user.options", function () {
mw.user.options.set( {
    "ccmeonemails": 0,
    "cols": 80,
    "date": "default",
    "diffonly": 0,
    "disablemail": 0,
    "disablesuggest": 0,
    "editfont": "default",
    "editondblclick": 0,
    "editsection": 1,
    "editsectiononrightclick": 0,
    "enotifminoredits": 0,
    "enotifrevealaddr": 0,
    "enotifusertalkpages": 1,
    "enotifwatchlistpages": 1,
    "extendwatchlist": 0,
    "fancysig": 0,
    "forceeditsummary": 0,
    "gender": "unknown",
    "hideminor": 0,
    "hidepatrolled": 0,
    "imagesize": 2,
    "justify": 0,
    "math": 6,
    "minordefault": 0,
    "newpageshidepatrolled": 0,
    "nocache": 0,
    "noconvertlink": 0,
    "norollbackdiff": 0,
    "numberheadings": 0,
    "previewonfirst": 0,
    "previewontop": 1,
    "rcdays": 7,
    "rclimit": 50,
    "rememberpassword": 0,
    "rows": 25,
    "searchlimit": 20,
    "showhiddencats": 0,
    "shownumberswatching": 1,
    "showtoc": 1,
    "showtoolbar": 1,
    "skin": "statexpflat",
    "stubthreshold": 0,
    "thumbsize": 2,
    "underline": 2,
    "uselivepreview": 0,
    "usenewrc": 0,
    "vector-simplesearch": 1,
    "watchcreations": 0,
    "watchdefault": 0,
    "watchdeletion": 0,
    "watchlistdays": 3,
    "watchlisthideanons": 0,
    "watchlisthidebots": 0,
    "watchlisthideliu": 0,
    "watchlisthideminor": 0,
    "watchlisthideown": 0,
    "watchlisthidepatrolled": 0,
    "watchmoves": 0,
    "wllimit": 250,
    "useeditwarning": 1,
    "prefershttps": 1,
    "flaggedrevsstable": 1,
    "usebetatoolbar": 1,
    "mathJax": true,
    "language": "en",
    "variant-gan": "gan",
    "variant-iu": "iu",
    "variant-kk": "kk",
    "variant-ku": "ku",
    "variant-shi": "shi",
    "variant-sr": "sr",
    "variant-tg": "tg",
    "variant-uz": "uz",
    "variant-zh": "zh",
    "searchNs0": true,
    "searchNs1": false,
    "searchNs2": false,
    "searchNs3": false,
    "searchNs4": false,
    "searchNs5": false,
    "searchNs6": false,
    "searchNs7": false,
    "searchNs8": false,
    "searchNs9": false,
    "searchNs10": false,
    "searchNs11": false,
    "searchNs12": false,
    "searchNs13": false,
    "searchNs14": false,
    "searchNs15": false,
    "searchNs100": false,
    "searchNs101": false,
    "searchNs104": false,
    "searchNs105": false,
    "searchNs108": false,
    "searchNs110": false,
    "searchNs111": false,
    "searchNs112": false,
    "searchNs113": false,
    "searchNs114": false,
    "searchNs120": false,
    "searchNs121": false,
    "searchNs122": false,
    "searchNs123": false,
    "searchNs124": false,
    "searchNs125": false,
    "searchNs126": false,
    "searchNs127": false,
    "searchNs128": false,
    "searchNs129": false,
    "searchNs130": false,
    "searchNs131": false,
    "searchNs132": false,
    "searchNs133": false,
    "searchNs134": false,
    "searchNs135": false,
    "searchNs154": false,
    "searchNs155": false,
    "variant": "en"
} );
}, {}, {} );
}</script>
<script>if(window.mw){
mw.loader.implement( "user.tokens", function () {
mw.user.tokens.set( {
    "editToken": "+\\",
    "patrolToken": false,
    "watchToken": false
} );
}, {}, {} );
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
<link href="/eurostat/statistics-explained/extensions/EditWarning/style.css" rel="stylesheet" type="text/css"/>
<script src="/eurostat/statistics-explained/extensions/StatexpVislet/StatexpVislet.js"></script><meta content="IE=edge" http-equiv="X-UA-Compatible"/><meta content="width=device-width, initial-scale=1.0" name="viewport"/><link href="/eurostat/statistics-explained/skins/statexpflat/css/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet"/><link href="/eurostat/statistics-explained/skins/statexpflat/css/statexpflat.css" rel="stylesheet"/><link href="/eurostat/statistics-explained/skins/statexpflat/css/statexpflat-grid.css" rel="stylesheet"/>
<script src="/eurostat/statistics-explained/skins/statexpflat/js/modernizr.custom.36138.js"></script>
<script src="/eurostat/statistics-explained/skins/statexpflat/js/css3-mediaqueries.js"></script><!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
			  <script src="/eurostat/statistics-explained/skins/statexpflat/js/html5shiv.min.js"></script>
			  <script src="/eurostat/statistics-explained/skins/statexpflat/js/respond.min.js"></script>
			<![endif]--></head>
<body class="mediawiki ltr sitedir-ltr ns-100 ns-subject page-Glossary_Country_codes skin-statexpflat action-view">
<!--

                <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.8";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

-->
<div class="container">
<div class="header" id="se-header">
<div class="grey-stripe"></div>
<div class="flag hidden-xs hidden-sm"></div>
<div class="flag-mobile hidden-md hidden-lg"></div>
<ul class="login list-inline hidden-xs hidden-sm">
<li><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Tutorial:Help_for_readers
">Tutorials</a></li>
<li><a accesskey="o" href="/eurostat/statistics-explained/index.php?title=Special:UserLogin&amp;returnto=Glossary%3ACountry+codes" title="Login is required to edit (reserved for Eurostat and accredited contributors)">log in</a></li>
<li class="login-icon"></li>
</ul>
<div class="heading">
<!--<div class="statexp-small hidden-lg hidden-md">Statistics Explained</div>-->
<div class="lighthouse articles visible-lg-block"></div>
<div class="alert alert-th3" style="

       position: absolute;
    z-index: 150;
    width: 300px;
    top: 60px;
    margin-left: 200px;
    background-color: #FF7900;
    color: #f9f9f9;
    font-weight: bolder;
    font-size: 12px;

"><p>Try the new automatic translation by clicking on the blue icon “Translate” up in the right corner of the article!</p></div>
<div class="links hidden-xs hidden-sm">
<ul class="list-inline">
<li class="lang-selector hidden-xs hidden-sm">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" id="lang-selector" type="button">
<a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes">English</a> <span class="caret"></span>
</button>
<ul aria-labelledby="dLabel" class="dropdown-menu" role="menu">
<li><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes/de">Deutsch</a></li>
<li><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes/fr">français</a></li>
</ul>
</div>
</li>
</ul>
</div>
<!----
		<div class="eurostat">eurostat</div>
		<div class="statexp">Statistics Explained</div>
		<!---->
<a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Main_Page"><div class="statexptitle"></div></a>
<div class="mobile-header-buttons hidden-md hidden-lg">
<button class="bt-open" id="mobile-menu-button">
<span class="glyphicon glyphicon-align-justify icon-show"></span>
<span class="glyphicon glyphicon-remove icon-hide"></span>
</button>
<button class="bt-open" id="mobile-search-button">
<span class="glyphicon glyphicon-search icon-show"></span>
<span class="glyphicon glyphicon-remove icon-hide"></span>
</button>
</div>
<!-- -->
<div class="search-box hidden-xs hidden-sm">
<form action="/eurostat/statistics-explained/index.php" class="form-inline" id="searchform">
<input name="title" type="hidden" value="Special:Search"/>
<div class="form-group">
<div class="input-group">
<input accesskey="f" class="form-control search-field" id="searchInput" name="search" placeholder="Search" title="Search Statistics Explained [f]" type="search"/> <span class="input-group-btn">
<button class="btn search-btn search-general" id="mw-searchButton" type="submit">
<span aria-hidden="true" class="glyphicon glyphicon-search"></span>
</button>
</span>
</div>
</div>
</form>
</div>
</div>
<div class="row hidden-xs hidden-sm">
<div class="col-lg-12" id="menu-bar-container">
<div class="row menu-bar-container">
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-navigation" type="button">
               Navigation              <span class="caret"></span>
</button>
<ul aria-labelledby="Navigation" class="dropdown-menu">
<li id="n-Home"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Main_Page">Main page</a></li>
<li id="n-Statistical-themes"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Statistical_themes">Statistical themes</a></li>
<li id="n-Glossary"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Thematic_glossaries">Glossary</a></li>
<li id="n-Categories"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Special:Categories">Categories</a></li>
<li id="n-Statistics-4-beginners"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Beginners:Statistics_4_beginners">Statistics 4 beginners</a></li>
<li id="n-Tutorials"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Tutorial:Help_for_readers
">Tutorials</a></li>
<li id="n-help"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
<li id="n-Eurostat-home"><a href="http://ec.europa.eu/eurostat/" rel="nofollow">Eurostat home</a></li>
<li id="n-Contact-Eurostat"><a href="http://ec.europa.eu/eurostat/help/support" rel="nofollow">Contact Eurostat</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-m-onlinepub" type="button">
               Online publications              <span class="caret"></span>
</button>
<ul aria-labelledby="Online publications" class="dropdown-menu">
<li id="n-Regional-yearbook"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Eurostat_regional_yearbook">Regional yearbook</a></li>
<li id="n-The-EU-in-the-world"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/The_EU_in_the_world">The EU in the world</a></li>
<li id="n-Other-publications"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Online publications">Full list</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-TOOLBOX" type="button">
Tools               <span class="caret"></span>
</button>
<ul aria-labelledby="" class="dropdown-menu">
<li id="t-whatlinkshere"><a accesskey="j" href="/eurostat/statistics-explained/index.php?title=Special:WhatLinksHere/Glossary:Country_codes" title="A list of all wiki pages that link here [j]">What links here</a></li> <li id="t-specialpages"><a accesskey="q" href="/eurostat/statistics-explained/index.php?title=Special:SpecialPages" title="A list of all special pages [q]">Special pages</a></li> </ul>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="row hidden-md hidden-lg">
<div class="col-sm-12 col-xs-12 mobile-search">
<div class="search-box search-box-mobile hidden-md hidden-lg">
<form action="/eurostat/statistics-explained/index.php" class="form-inline" id="searchform">
<input name="title" type="hidden" value="Special:Search"/>
<div class="form-group">
<div class="input-group">
<input accesskey="f" class="form-control search-field" id="searchInput" name="search" placeholder="Search" title="Search Statistics Explained [f]" type="search"/> <span class="input-group-btn">
<button class="btn search-btn search-general" id="mw-searchButton" type="submit">
<span aria-hidden="true" class="glyphicon glyphicon-search"></span>
</button>
</span>
</div>
</div>
</form>
</div>
</div>
<div class="col-sm-12 col-xs-12 mobile-menu">
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-navigation" type="button">
               Navigation              <span class="caret"></span>
</button>
<ul aria-labelledby="Navigation" class="dropdown-menu">
<li id="n-Home"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Main_Page">Main page</a></li>
<li id="n-Statistical-themes"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Statistical_themes">Statistical themes</a></li>
<li id="n-Glossary"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Thematic_glossaries">Glossary</a></li>
<li id="n-Categories"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Special:Categories">Categories</a></li>
<li id="n-Statistics-4-beginners"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Beginners:Statistics_4_beginners">Statistics 4 beginners</a></li>
<li id="n-Tutorials"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Tutorial:Help_for_readers
">Tutorials</a></li>
<li id="n-help"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
<li id="n-Eurostat-home"><a href="http://ec.europa.eu/eurostat/" rel="nofollow">Eurostat home</a></li>
<li id="n-Contact-Eurostat"><a href="http://ec.europa.eu/eurostat/help/support" rel="nofollow">Contact Eurostat</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-m-onlinepub" type="button">
               Online publications              <span class="caret"></span>
</button>
<ul aria-labelledby="Online publications" class="dropdown-menu">
<li id="n-Regional-yearbook"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Eurostat_regional_yearbook">Regional yearbook</a></li>
<li id="n-The-EU-in-the-world"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/The_EU_in_the_world">The EU in the world</a></li>
<li id="n-Other-publications"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Online publications">Full list</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-TOOLBOX" type="button">
Tools               <span class="caret"></span>
</button>
<ul aria-labelledby="" class="dropdown-menu">
<li id="t-whatlinkshere"><a accesskey="j" href="/eurostat/statistics-explained/index.php?title=Special:WhatLinksHere/Glossary:Country_codes" title="A list of all wiki pages that link here [j]">What links here</a></li> <li id="t-specialpages"><a accesskey="q" href="/eurostat/statistics-explained/index.php?title=Special:SpecialPages" title="A list of all special pages [q]">Special pages</a></li> </ul>
</div>
</div>
</div>
</div>
<!--END HEADER BEGIN PAGE-->
<!----
<div class="onerow">
<!---->
<div class="row content-row">
<!-- BEGIN LSF -->
<!-- -->
<div class="hidden-md hidden-lg hidden-xs hidden-sm sidebar content-col">
<!----
		<div class="col2 sidebar">
		<!---->
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-navigation" type="button">
               Navigation              <span class="caret"></span>
</button>

In [86]:
div = soup.find('div', {'class':'mw-content-ltr'})

In [87]:
div

<div class="mw-content-ltr" dir="ltr" id="mw-content-text" lang="en"><p>Member States of the <a href="/eurostat/statistics-explained/index.php?title=Glossary:European_Union_(EU)" title="Glossary:European Union (EU)">European Union (EU)</a> and other countries have been assigned a two-letter <b>country code</b>, always written in capital letters, and often used as an abbreviation in statistical analyses, tables, figures or maps.
</p><p><br/>
The <b>protocol order</b> in which countries are often listed is based on the alphabetical list of countries in their national language for EU and <a href="/eurostat/statistics-explained/index.php?title=Glossary:European_Free_Trade_Association_(EFTA)" title="Glossary:European Free Trade Association (EFTA)">EFTA</a> Member States and for <a href="/eurostat/statistics-explained/index.php?title=Glossary:Candidate_countries" title="Glossary:Candidate countries">candidate countries</a>; for <a class="mw-redirect" href="/eurostat/statistics-explained/index.php?title=Glossary:Potential_candidates" title="Glossary:Potential candidates">potential candidates</a>, it is based on the alphabetical order of their country code.
</p><p>EU Member States come first, followed by <a href="/eurostat/statistics-explained/index.php?title=Glossary:European_Free_Trade_Association_(EFTA)" title="Glossary:European Free Trade Association (EFTA)">European Free Trade Association (EFTA)</a> Member States, candidate countries for EU membership, potential candidates and, finally, other countries. The order in the tables below is first column down, then second column down, etc..
</p><p><b>European Union (EU)</b>
</p>
<table border="1" cellpadding="2" cellspacing="0" style="vertical-align:top;background-color:#f5faff" width="80%">
<tr>
<td>Belgium
</td>
<td>(BE)
</td>
<td>Greece
</td>
<td>(EL)
</td>
<td>Lithuania
</td>
<td>(LT)
</td>
<td>Portugal
</td>
<td>(PT)
</td></tr>
<tr>
<td>Bulgaria
</td>
<td>(BG)
</td>
<td>Spain
</td>
<td>(ES)
</td>
<td>Luxembourg
</td>
<td>(LU)
</td>
<td>Romania
</td>
<td>(RO)
</td></tr>
<tr>
<td>Czechia
</td>
<td>(CZ)
</td>
<td>France
</td>
<td>(FR)
</td>
<td>Hungary
</td>
<td>(HU)
</td>
<td>Slovenia
</td>
<td>(SI)
</td></tr>
<tr>
<td>Denmark
</td>
<td>(DK)
</td>
<td>Croatia
</td>
<td>(HR)
</td>
<td>Malta
</td>
<td>(MT)
</td>
<td>Slovakia
</td>
<td>(SK)
</td></tr>
<tr>
<td>Germany
</td>
<td>(DE)
</td>
<td>Italy
</td>
<td>(IT)
</td>
<td>Netherlands
</td>
<td>(NL)
</td>
<td>Finland
</td>
<td>(FI)
</td></tr>
<tr>
<td>Estonia
</td>
<td>(EE)
</td>
<td>Cyprus
</td>
<td>(CY)
</td>
<td>Austria
</td>
<td>(AT)
</td>
<td>Sweden
</td>
<td>(SE)
</td></tr>
<tr>
<td>Ireland
</td>
<td>(IE)
</td>
<td>Latvia
</td>
<td>(LV)
</td>
<td>Poland
</td>
<td>(PL)
</td></tr></table>
<p><b>European Free Trade Association (EFTA)</b>
</p>
<table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="35%">
<tr>
<td> Iceland
</td>
<td> (IS)
</td>
<td>
</td>
<td> Norway
</td>
<td> (NO)
</td></tr>
<tr>
<td> Liechtenstein
</td>
<td> (LI)
</td>
<td>
</td>
<td> Switzerland
</td>
<td> (CH)
</td></tr></table>
<p><b>United Kingdom</b>
</p>
<table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="35%">
<tr>
<td> United Kingdom
</td>
<td> (UK)
</td>
<td>
</td></tr></table>
<p><b>EU candidate countries</b>
</p>
<table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="50%">
<tr>
<td> Montenegro
</td>
<td> (ME)
</td></tr>
<tr>
<td> North Macedonia
</td>
<td> (MK)
</td></tr>
<tr>
<td> Albania
</td>
<td> (AL)
</td></tr>
<tr>
<td>Serbia
</td>
<td> (RS)
</td></tr>
<tr>
<td> Turkey
</td>
<td> (TR)
</td></tr></table>
<p><b>Potential candidates (all other Western Balkan countries)</b>
</p>
<table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="50%">
<tr>
<td> Bosnia and Herzegovina
</td>
<td> (BA)
</td></tr>
<tr>
<td> Kosovo*
</td>
<td> (XK<sup class="reference" id="cite_ref-1"><a href="#cite_note-1">[1]</a></sup>)
</td></tr>
</table>
<p><b><a href="/eurostat/statistics-explained/index.php?title=Glossary:European_Neighbourhood_Policy_(ENP)" title="Glossary:European Neighbourhood Policy (ENP)">European Neighbourhood Policy (ENP)</a>-East</b> countries:
</p>
<table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="50%">
<tr>
<td> Armenia
</td>
<td> (AM)
</td>
<td>
</td>
<td> Belarus
</td>
<td> (BY)
</td>
<td>
</td>
<td> Georgia
</td>
<td> (GE)
</td></tr>
<tr>
<td> Azerbaijan
</td>
<td> (AZ)
</td>
<td>
</td>
<td> Moldova
</td>
<td> (MD)
</td>
<td>
</td>
<td> Ukraine
</td>
<td> (UA)
</td></tr></table>
<p><b>European Neighbourhood Policy (ENP)-South</b> countries:
</p>
<table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="50%">
<tr>
<td> Algeria
</td>
<td> (DZ)
</td>
<td>
</td>
<td> Lebanon
</td>
<td> (LB)
</td>
<td>
</td>
<td> Syria
</td>
<td> (SY)
</td></tr>
<tr>
<td> Egypt
</td>
<td> (EG)
</td>
<td>
</td>
<td> Libya
</td>
<td> (LY)
</td>
<td>
</td>
<td> Tunisia
</td>
<td> (TN)
</td></tr>
<tr>
<td> Israel
</td>
<td> (IL)
</td>
<td>
</td>
<td> Morocco
</td>
<td> (MA)
</td>
<td>
</td>
<td>
</td>
<td>
</td></tr>
<tr>
<td> Jordan
</td>
<td> (JO)
</td>
<td>
</td>
<td> Palestine <sup class="reference" id="cite_ref-2"><a href="#cite_note-2">[2]</a></sup>
</td>
<td> (PS)
</td>
<td>
</td>
<td>
</td>
<td>
</td></tr></table>
<p><b>Other European countries</b>
</p>
<table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="50%">
<tr>
<td> Russia
</td>
<td> (RU)
</td></tr></table>
<p><b>Non-European countries</b>
</p>
<table border="1" cellpadding="2" cellspacing="0" style="vertical-align:top;background-color:#f5faff" width="80%">
<tr>
<td>Argentina
</td>
<td>(AR)
</td>
<td>
</td>
<td>China (except Hong Kong)
</td>
<td>(CN_X_HK)
</td>
<td>
</td>
<td>Mexico
</td>
<td>(MX)
</td>
<td>
</td>
<td>South Africa
</td>
<td>(ZA)
</td></tr>
<tr>
<td>Australia
</td>
<td>(AU)
</td>
<td>
</td>
<td>Hong Kong
</td>
<td>(HK)
</td>
<td>
</td>
<td>Nigeria
</td>
<td>(NG)
</td>
<td>
</td>
<td>South Korea
</td>
<td>(KR)
</td></tr>
<tr>
<td>Brazil
</td>
<td>(BR)
</td>
<td>
</td>
<td>India
</td>
<td>(IN)
</td>
<td>
</td>
<td>New Zealand
</td>
<td>(NZ)
</td>
<td>
</td>
<td>Taiwan
</td>
<td>(TW)
</td></tr>
<tr>
<td>Canada
</td>
<td>(CA)
</td>
<td>
</td>
<td>Japan
</td>
<td>(JP)
</td>
<td>
</td>
<td>Singapore
</td>
<td>(SG)
</td>
<td>
</td>
<td>United States
</td>
<td>(US)
</td></tr></table>
<p>(*) <i>This designation is without prejudice to positions on status, and is in line with UNSCR 1244/1999 and the ICJ Opinion on the Kosovo declaration of independence.</i>
(with asterisk and footnote in written documents, only the first time that Kosovo is mentioned).
</p>
<h2><span class="mw-headline" id="Further_information">Further information</span></h2>
<ul>
<li> <a class="external text" href="https://ec.europa.eu/neighbourhood-enlargement/countries/detailed-country-information/north-macedonia_en" rel="nofollow">DG NEAR web site for North Macedonia</a>
</li>
<li> <a class="external text" href="http://ec.europa.eu/enlargement/countries/detailed-country-information/kosovo/index_en.htm" rel="nofollow">DG NEAR web site for Kosovo</a>
</li>
<li> <a class="external text" href="http://ec.europa.eu/enlargement/neighbourhood/countries/palestine/index_en.htm" rel="nofollow">DG NEAR web site for Palestine</a>
</li>
</ul>
<h2><span class="mw-headline" id="Related_concepts">Related concepts</span></h2>
<ul>
<li><a href="/eurostat/statistics-explained/index.php?title=Glossary:Currency_codes" title="Glossary:Currency codes">Currency codes</a>
</li>
<li><a href="/eurostat/statistics-explained/index.php?title=Glossary:Language_codes" title="Glossary:Language codes">Language codes</a>
</li>
</ul>
<h2><span class="mw-headline" id="External_links">External links</span></h2>
<p><a class="external text" href="http://publications.europa.eu/code/en/en-000300.htm" rel="nofollow">Interinstitutional style guide (Publications Office)</a>
</p>
<h2><span class="mw-headline" id="Notes">Notes</span></h2>
<ol class="references">
<li id="cite_note-1"><span class="mw-cite-backlink"><a href="#cite_ref-1">↑</a></span> <span class="reference-text">'XK' is a code used for practical reasons and not an official ISO country code.</span>
</li>
<li id="cite_note-2"><span class="mw-cite-backlink"><a href="#cite_ref-2">↑</a></span> <span class="reference-text">This designation shall not be
construed as recognition of a State of Palestine and is without prejudice to the individual
positions of the Member States on this issue.</span>
</li>
</ol>
<!--
NewPP limit report
CPU time usage: 0.022 seconds
Real time usage: 0.026 seconds
Preprocessor visited node count: 59/1000000
Preprocessor generated node count: 182/1000000
Post‐expand include size: 0/2097152 bytes
Template argument size: 0/2097152 bytes
Highest expansion depth: 3/40
Expensive parser function count: 0/100
-->
</div>

In [88]:
soup.find('table')

<table border="1" cellpadding="2" cellspacing="0" style="vertical-align:top;background-color:#f5faff" width="80%">
<tr>
<td>Belgium
</td>
<td>(BE)
</td>
<td>Greece
</td>
<td>(EL)
</td>
<td>Lithuania
</td>
<td>(LT)
</td>
<td>Portugal
</td>
<td>(PT)
</td></tr>
<tr>
<td>Bulgaria
</td>
<td>(BG)
</td>
<td>Spain
</td>
<td>(ES)
</td>
<td>Luxembourg
</td>
<td>(LU)
</td>
<td>Romania
</td>
<td>(RO)
</td></tr>
<tr>
<td>Czechia
</td>
<td>(CZ)
</td>
<td>France
</td>
<td>(FR)
</td>
<td>Hungary
</td>
<td>(HU)
</td>
<td>Slovenia
</td>
<td>(SI)
</td></tr>
<tr>
<td>Denmark
</td>
<td>(DK)
</td>
<td>Croatia
</td>
<td>(HR)
</td>
<td>Malta
</td>
<td>(MT)
</td>
<td>Slovakia
</td>
<td>(SK)
</td></tr>
<tr>
<td>Germany
</td>
<td>(DE)
</td>
<td>Italy
</td>
<td>(IT)
</td>
<td>Netherlands
</td>
<td>(NL)
</td>
<td>Finland
</td>
<td>(FI)
</td></tr>
<tr>
<td>Estonia
</td>
<td>(EE)
</td>
<td>Cyprus
</td>
<td>(CY)
</td>
<td>Austria
</td>
<td>(AT)
</td>
<td>Sweden
</td>
<td>(SE)
</td></tr>
<tr>
<td>Ireland
</td>
<td>(IE)
</td>
<td>Latvia
</td>
<td>(LV)
</td>
<td>Poland
</td>
<td>(PL)
</td></tr></table>

In [89]:
all_tables = soup.find_all('table')

all_tables

[<table border="1" cellpadding="2" cellspacing="0" style="vertical-align:top;background-color:#f5faff" width="80%">
 <tr>
 <td>Belgium
 </td>
 <td>(BE)
 </td>
 <td>Greece
 </td>
 <td>(EL)
 </td>
 <td>Lithuania
 </td>
 <td>(LT)
 </td>
 <td>Portugal
 </td>
 <td>(PT)
 </td></tr>
 <tr>
 <td>Bulgaria
 </td>
 <td>(BG)
 </td>
 <td>Spain
 </td>
 <td>(ES)
 </td>
 <td>Luxembourg
 </td>
 <td>(LU)
 </td>
 <td>Romania
 </td>
 <td>(RO)
 </td></tr>
 <tr>
 <td>Czechia
 </td>
 <td>(CZ)
 </td>
 <td>France
 </td>
 <td>(FR)
 </td>
 <td>Hungary
 </td>
 <td>(HU)
 </td>
 <td>Slovenia
 </td>
 <td>(SI)
 </td></tr>
 <tr>
 <td>Denmark
 </td>
 <td>(DK)
 </td>
 <td>Croatia
 </td>
 <td>(HR)
 </td>
 <td>Malta
 </td>
 <td>(MT)
 </td>
 <td>Slovakia
 </td>
 <td>(SK)
 </td></tr>
 <tr>
 <td>Germany
 </td>
 <td>(DE)
 </td>
 <td>Italy
 </td>
 <td>(IT)
 </td>
 <td>Netherlands
 </td>
 <td>(NL)
 </td>
 <td>Finland
 </td>
 <td>(FI)
 </td></tr>
 <tr>
 <td>Estonia
 </td>
 <td>(EE)
 </td>
 <td>Cyprus
 </td>
 <td>(CY)
 </td>
 <td>Austria
 </td>
 <td>(AT)
 </td>
 <td>Sweden
 </td>
 <td>(SE)
 </td></tr>
 <tr>
 <td>Ireland
 </td>
 <td>(IE)
 </td>
 <td>Latvia
 </td>
 <td>(LV)
 </td>
 <td>Poland
 </td>
 <td>(PL)
 </td></tr></table>,
 <table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="35%">
 <tr>
 <td> Iceland
 </td>
 <td> (IS)
 </td>
 <td>
 </td>
 <td> Norway
 </td>
 <td> (NO)
 </td></tr>
 <tr>
 <td> Liechtenstein
 </td>
 <td> (LI)
 </td>
 <td>
 </td>
 <td> Switzerland
 </td>
 <td> (CH)
 </td></tr></table>,
 <table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="35%">
 <tr>
 <td> United Kingdom
 </td>
 <td> (UK)
 </td>
 <td>
 </td></tr></table>,
 <table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="50%">
 <tr>
 <td> Montenegro
 </td>
 <td> (ME)
 </td></tr>
 <tr>
 <td> North Macedonia
 </td>
 <td> (MK)
 </td></tr>
 <tr>
 <td> Albania
 </td>
 <td> (AL)
 </td></tr>
 <tr>
 <td>Serbia
 </td>
 <td> (RS)
 </td></tr>
 <tr>
 <td> Turkey
 </td>
 <td> (TR)
 </td></tr></table>,
 <table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="50%">
 <tr>
 <td> Bosnia and Herzegovina
 </td>
 <td> (BA)
 </td></tr>
 <tr>
 <td> Kosovo*
 </td>
 <td> (XK<sup class="reference" id="cite_ref-1"><a href="#cite_note-1">[1]</a></sup>)
 </td></tr>
 </table>,
 <table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="50%">
 <tr>
 <td> Armenia
 </td>
 <td> (AM)
 </td>
 <td>
 </td>
 <td> Belarus
 </td>
 <td> (BY)
 </td>
 <td>
 </td>
 <td> Georgia
 </td>
 <td> (GE)
 </td></tr>
 <tr>
 <td> Azerbaijan
 </td>
 <td> (AZ)
 </td>
 <td>
 </td>
 <td> Moldova
 </td>
 <td> (MD)
 </td>
 <td>
 </td>
 <td> Ukraine
 </td>
 <td> (UA)
 </td></tr></table>,
 <table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="50%">
 <tr>
 <td> Algeria
 </td>
 <td> (DZ)
 </td>
 <td>
 </td>
 <td> Lebanon
 </td>
 <td> (LB)
 </td>
 <td>
 </td>
 <td> Syria
 </td>
 <td> (SY)
 </td></tr>
 <tr>
 <td> Egypt
 </td>
 <td> (EG)
 </td>
 <td>
 </td>
 <td> Libya
 </td>
 <td> (LY)
 </td>
 <td>
 </td>
 <td> Tunisia
 </td>
 <td> (TN)
 </td></tr>
 <tr>
 <td> Israel
 </td>
 <td> (IL)
 </td>
 <td>
 </td>
 <td> Morocco
 </td>
 <td> (MA)
 </td>
 <td>
 </td>
 <td>
 </td>
 <td>
 </td></tr>
 <tr>
 <td> Jordan
 </td>
 <td> (JO)
 </td>
 <td>
 </td>
 <td> Palestine <sup class="reference" id="cite_ref-2"><a href="#cite_note-2">[2]</a></sup>
 </td>
 <td> (PS)
 </td>
 <td>
 </td>
 <td>
 </td>
 <td>
 </td></tr></table>,
 <table border="1" cellpadding="2" cellspacing="0" style="background-color: #f5faff; vertical-align: top" width="50%">
 <tr>
 <td> Russia
 </td>
 <td> (RU)
 </td></tr></table>,
 <table border="1" cellpadding="2" cellspacing="0" style="vertical-align:top;background-color:#f5faff" width="80%">
 <tr>
 <td>Argentina
 </td>
 <td>(AR)
 </td>
 <td>
 </td>
 <td>China (except Hong Kong)
 </td>
 <td>(CN_X_HK)
 </td>
 <td>
 </td>
 <td>Mexico
 </td>
 <td>(MX)
 </td>
 <td>
 </td>
 <td>South Africa
 </td>
 <td>(ZA)
 </td></tr>
 <tr>
 <td>Australia
 </td>
 <td>(AU)
 </td>
 <td>
 </td>
 <td>Hong Kong
 </td>
 <td>(HK)
 </td>
 <td>
 </td>
 <td>Nigeria
 </td>
 <td>(NG)
 </td>
 <td>
 </td>
 <td>South Korea
 </td>
 <td>(KR)
 </td></tr>
 <tr>
 <td>Brazil
 </td>
 <td>(BR)
 </td>
 <td>
 </td>
 <td>India
 </td>
 <td>(IN)
 </td>
 <td>
 </td>
 <td>New Zealand
 </td>
 <td>(NZ)
 </td>
 <td>
 </td>
 <td>Taiwan
 </td>
 <td>(TW)
 </td></tr>
 <tr>
 <td>Canada
 </td>
 <td>(CA)
 </td>
 <td>
 </td>
 <td>Japan
 </td>
 <td>(JP)
 </td>
 <td>
 </td>
 <td>Singapore
 </td>
 <td>(SG)
 </td>
 <td>
 </td>
 <td>United States
 </td>
 <td>(US)
 </td></tr></table>]

In [90]:
rows = soup.select('td')

rows

[<td>Belgium
 </td>,
 <td>(BE)
 </td>,
 <td>Greece
 </td>,
 <td>(EL)
 </td>,
 <td>Lithuania
 </td>,
 <td>(LT)
 </td>,
 <td>Portugal
 </td>,
 <td>(PT)
 </td>,
 <td>Bulgaria
 </td>,
 <td>(BG)
 </td>,
 <td>Spain
 </td>,
 <td>(ES)
 </td>,
 <td>Luxembourg
 </td>,
 <td>(LU)
 </td>,
 <td>Romania
 </td>,
 <td>(RO)
 </td>,
 <td>Czechia
 </td>,
 <td>(CZ)
 </td>,
 <td>France
 </td>,
 <td>(FR)
 </td>,
 <td>Hungary
 </td>,
 <td>(HU)
 </td>,
 <td>Slovenia
 </td>,
 <td>(SI)
 </td>,
 <td>Denmark
 </td>,
 <td>(DK)
 </td>,
 <td>Croatia
 </td>,
 <td>(HR)
 </td>,
 <td>Malta
 </td>,
 <td>(MT)
 </td>,
 <td>Slovakia
 </td>,
 <td>(SK)
 </td>,
 <td>Germany
 </td>,
 <td>(DE)
 </td>,
 <td>Italy
 </td>,
 <td>(IT)
 </td>,
 <td>Netherlands
 </td>,
 <td>(NL)
 </td>,
 <td>Finland
 </td>,
 <td>(FI)
 </td>,
 <td>Estonia
 </td>,
 <td>(EE)
 </td>,
 <td>Cyprus
 </td>,
 <td>(CY)
 </td>,
 <td>Austria
 </td>,
 <td>(AT)
 </td>,
 <td>Sweden
 </td>,
 <td>(SE)
 </td>,
 <td>Ireland
 </td>,
 <td>(IE)
 </td>,
 <td>Latvia
 </td>,
 <td>(LV)
 </td>,
 <td>Poland
 </td>,
 <td>(PL)
 </td>,
 <td> Iceland
 </td>,
 <td> (IS)
 </td>,
 <td>
 </td>,
 <td> Norway
 </td>,
 <td> (NO)
 </td>,
 <td> Liechtenstein
 </td>,
 <td> (LI)
 </td>,
 <td>
 </td>,
 <td> Switzerland
 </td>,
 <td> (CH)
 </td>,
 <td> United Kingdom
 </td>,
 <td> (UK)
 </td>,
 <td>
 </td>,
 <td> Montenegro
 </td>,
 <td> (ME)
 </td>,
 <td> North Macedonia
 </td>,
 <td> (MK)
 </td>,
 <td> Albania
 </td>,
 <td> (AL)
 </td>,
 <td>Serbia
 </td>,
 <td> (RS)
 </td>,
 <td> Turkey
 </td>,
 <td> (TR)
 </td>,
 <td> Bosnia and Herzegovina
 </td>,
 <td> (BA)
 </td>,
 <td> Kosovo*
 </td>,
 <td> (XK<sup class="reference" id="cite_ref-1"><a href="#cite_note-1">[1]</a></sup>)
 </td>,
 <td> Armenia
 </td>,
 <td> (AM)
 </td>,
 <td>
 </td>,
 <td> Belarus
 </td>,
 <td> (BY)
 </td>,
 <td>
 </td>,
 <td> Georgia
 </td>,
 <td> (GE)
 </td>,
 <td> Azerbaijan
 </td>,
 <td> (AZ)
 </td>,
 <td>
 </td>,
 <td> Moldova
 </td>,
 <td> (MD)
 </td>,
 <td>
 </td>,
 <td> Ukraine
 </td>,
 <td> (UA)
 </td>,
 <td> Algeria
 </td>,
 <td> (DZ)
 </td>,
 <td>
 </td>,
 <td> Lebanon
 </td>,
 <td> (LB)
 </td>,
 <td>
 </td>,
 <td> Syria
 </td>,
 <td> (SY)
 </td>,
 <td> Egypt
 </td>,
 <td> (EG)
 </td>,
 <td>
 </td>,
 <td> Libya
 </td>,
 <td> (LY)
 </td>,
 <td>
 </td>,
 <td> Tunisia
 </td>,
 <td> (TN)
 </td>,
 <td> Israel
 </td>,
 <td> (IL)
 </td>,
 <td>
 </td>,
 <td> Morocco
 </td>,
 <td> (MA)
 </td>,
 <td>
 </td>,
 <td>
 </td>,
 <td>
 </td>,
 <td> Jordan
 </td>,
 <td> (JO)
 </td>,
 <td>
 </td>,
 <td> Palestine <sup class="reference" id="cite_ref-2"><a href="#cite_note-2">[2]</a></sup>
 </td>,
 <td> (PS)
 </td>,
 <td>
 </td>,
 <td>
 </td>,
 <td>
 </td>,
 <td> Russia
 </td>,
 <td> (RU)
 </td>,
 <td>Argentina
 </td>,
 <td>(AR)
 </td>,
 <td>
 </td>,
 <td>China (except Hong Kong)
 </td>,
 <td>(CN_X_HK)
 </td>,
 <td>
 </td>,
 <td>Mexico
 </td>,
 <td>(MX)
 </td>,
 <td>
 </td>,
 <td>South Africa
 </td>,
 <td>(ZA)
 </td>,
 <td>Australia
 </td>,
 <td>(AU)
 </td>,
 <td>
 </td>,
 <td>Hong Kong
 </td>,
 <td>(HK)
 </td>,
 <td>
 </td>,
 <td>Nigeria
 </td>,
 <td>(NG)
 </td>,
 <td>
 </td>,
 <td>South Korea
 </td>,
 <td>(KR)
 </td>,
 <td>Brazil
 </td>,
 <td>(BR)
 </td>,
 <td>
 </td>,
 <td>India
 </td>,
 <td>(IN)
 </td>,
 <td>
 </td>,
 <td>New Zealand
 </td>,
 <td>(NZ)
 </td>,
 <td>
 </td>,
 <td>Taiwan
 </td>,
 <td>(TW)
 </td>,
 <td>Canada
 </td>,
 <td>(CA)
 </td>,
 <td>
 </td>,
 <td>Japan
 </td>,
 <td>(JP)
 </td>,
 <td>
 </td>,
 <td>Singapore
 </td>,
 <td>(SG)
 </td>,
 <td>
 </td>,
 <td>United States
 </td>,
 <td>(US)
 </td>]

In [91]:
text_rows=[]

for i in soup.select("td"):
    text_rows.append(i.text)

print(text_rows)

['Belgium\n', '(BE)\n', 'Greece\n', '(EL)\n', 'Lithuania\n', '(LT)\n', 'Portugal\n', '(PT)\n', 'Bulgaria\n', '(BG)\n', 'Spain\n', '(ES)\n', 'Luxembourg\n', '(LU)\n', 'Romania\n', '(RO)\n', 'Czechia\n', '(CZ)\n', 'France\n', '(FR)\n', 'Hungary\n', '(HU)\n', 'Slovenia\n', '(SI)\n', 'Denmark\n', '(DK)\n', 'Croatia\n', '(HR)\n', 'Malta\n', '(MT)\n', 'Slovakia\n', '(SK)\n', 'Germany\n', '(DE)\n', 'Italy\n', '(IT)\n', 'Netherlands\n', '(NL)\n', 'Finland\n', '(FI)\n', 'Estonia\n', '(EE)\n', 'Cyprus\n', '(CY)\n', 'Austria\n', '(AT)\n', 'Sweden\n', '(SE)\n', 'Ireland\n', '(IE)\n', 'Latvia\n', '(LV)\n', 'Poland\n', '(PL)\n', ' Iceland\n', ' (IS)\n', '\n', ' Norway\n', ' (NO)\n', ' Liechtenstein\n', ' (LI)\n', '\n', ' Switzerland\n', ' (CH)\n', ' United Kingdom\n', ' (UK)\n', '\n', ' Montenegro\n', ' (ME)\n', ' North Macedonia\n', ' (MK)\n', ' Albania\n', ' (AL)\n', 'Serbia\n', ' (RS)\n', ' Turkey\n', ' (TR)\n', ' Bosnia and Herzegovina\n', ' (BA)\n', ' Kosovo*\n', ' (XK[1])\n', ' Armenia\n', ' (AM)\n', '\n', ' Belarus\n', ' (BY)\n', '\n', ' Georgia\n', ' (GE)\n', ' Azerbaijan\n', ' (AZ)\n', '\n', ' Moldova\n', ' (MD)\n', '\n', ' Ukraine\n', ' (UA)\n', ' Algeria\n', ' (DZ)\n', '\n', ' Lebanon\n', ' (LB)\n', '\n', ' Syria\n', ' (SY)\n', ' Egypt\n', ' (EG)\n', '\n', ' Libya\n', ' (LY)\n', '\n', ' Tunisia\n', ' (TN)\n', ' Israel\n', ' (IL)\n', '\n', ' Morocco\n', ' (MA)\n', '\n', ' \xa0\n', ' \xa0\n', ' Jordan\n', ' (JO)\n', '\n', ' Palestine [2]\n', ' (PS)\n', '\n', ' \xa0\n', ' \xa0\n', ' Russia\n', ' (RU)\n', 'Argentina\n', '(AR)\n', '\n', 'China (except Hong Kong)\n', '(CN_X_HK)\n', '\n', 'Mexico\n', '(MX)\n', '\n', 'South Africa\n', '(ZA)\n', 'Australia\n', '(AU)\n', '\n', 'Hong Kong\n', '(HK)\n', '\n', 'Nigeria\n', '(NG)\n', '\n', 'South Korea\n', '(KR)\n', 'Brazil\n', '(BR)\n', '\n', 'India\n', '(IN)\n', '\n', 'New Zealand\n', '(NZ)\n', '\n', 'Taiwan\n', '(TW)\n', 'Canada\n', '(CA)\n', '\n', 'Japan\n', '(JP)\n', '\n', 'Singapore\n', '(SG)\n', '\n', 'United States\n', '(US)\n']

In [92]:
clean_rows=[]

for i in iter(text_rows):
    clean_rows = [i.replace('\n','') for i in text_rows]

print(clean_rows)

['Belgium', '(BE)', 'Greece', '(EL)', 'Lithuania', '(LT)', 'Portugal', '(PT)', 'Bulgaria', '(BG)', 'Spain', '(ES)', 'Luxembourg', '(LU)', 'Romania', '(RO)', 'Czechia', '(CZ)', 'France', '(FR)', 'Hungary', '(HU)', 'Slovenia', '(SI)', 'Denmark', '(DK)', 'Croatia', '(HR)', 'Malta', '(MT)', 'Slovakia', '(SK)', 'Germany', '(DE)', 'Italy', '(IT)', 'Netherlands', '(NL)', 'Finland', '(FI)', 'Estonia', '(EE)', 'Cyprus', '(CY)', 'Austria', '(AT)', 'Sweden', '(SE)', 'Ireland', '(IE)', 'Latvia', '(LV)', 'Poland', '(PL)', ' Iceland', ' (IS)', '', ' Norway', ' (NO)', ' Liechtenstein', ' (LI)', '', ' Switzerland', ' (CH)', ' United Kingdom', ' (UK)', '', ' Montenegro', ' (ME)', ' North Macedonia', ' (MK)', ' Albania', ' (AL)', 'Serbia', ' (RS)', ' Turkey', ' (TR)', ' Bosnia and Herzegovina', ' (BA)', ' Kosovo*', ' (XK[1])', ' Armenia', ' (AM)', '', ' Belarus', ' (BY)', '', ' Georgia', ' (GE)', ' Azerbaijan', ' (AZ)', '', ' Moldova', ' (MD)', '', ' Ukraine', ' (UA)', ' Algeria', ' (DZ)', '', ' Lebanon', ' (LB)', '', ' Syria', ' (SY)', ' Egypt', ' (EG)', '', ' Libya', ' (LY)', '', ' Tunisia', ' (TN)', ' Israel', ' (IL)', '', ' Morocco', ' (MA)', '', ' \xa0', ' \xa0', ' Jordan', ' (JO)', '', ' Palestine [2]', ' (PS)', '', ' \xa0', ' \xa0', ' Russia', ' (RU)', 'Argentina', '(AR)', '', 'China (except Hong Kong)', '(CN_X_HK)', '', 'Mexico', '(MX)', '', 'South Africa', '(ZA)', 'Australia', '(AU)', '', 'Hong Kong', '(HK)', '', 'Nigeria', '(NG)', '', 'South Korea', '(KR)', 'Brazil', '(BR)', '', 'India', '(IN)', '', 'New Zealand', '(NZ)', '', 'Taiwan', '(TW)', 'Canada', '(CA)', '', 'Japan', '(JP)', '', 'Singapore', '(SG)', '', 'United States', '(US)']

In [93]:
clean_rows[0]

'Belgium'

In [94]:
clean_rows[1]

'(BE)'

In [95]:
print(clean_rows)

['Belgium', '(BE)', 'Greece', '(EL)', 'Lithuania', '(LT)', 'Portugal', '(PT)', 'Bulgaria', '(BG)', 'Spain', '(ES)', 'Luxembourg', '(LU)', 'Romania', '(RO)', 'Czechia', '(CZ)', 'France', '(FR)', 'Hungary', '(HU)', 'Slovenia', '(SI)', 'Denmark', '(DK)', 'Croatia', '(HR)', 'Malta', '(MT)', 'Slovakia', '(SK)', 'Germany', '(DE)', 'Italy', '(IT)', 'Netherlands', '(NL)', 'Finland', '(FI)', 'Estonia', '(EE)', 'Cyprus', '(CY)', 'Austria', '(AT)', 'Sweden', '(SE)', 'Ireland', '(IE)', 'Latvia', '(LV)', 'Poland', '(PL)', ' Iceland', ' (IS)', '', ' Norway', ' (NO)', ' Liechtenstein', ' (LI)', '', ' Switzerland', ' (CH)', ' United Kingdom', ' (UK)', '', ' Montenegro', ' (ME)', ' North Macedonia', ' (MK)', ' Albania', ' (AL)', 'Serbia', ' (RS)', ' Turkey', ' (TR)', ' Bosnia and Herzegovina', ' (BA)', ' Kosovo*', ' (XK[1])', ' Armenia', ' (AM)', '', ' Belarus', ' (BY)', '', ' Georgia', ' (GE)', ' Azerbaijan', ' (AZ)', '', ' Moldova', ' (MD)', '', ' Ukraine', ' (UA)', ' Algeria', ' (DZ)', '', ' Lebanon', ' (LB)', '', ' Syria', ' (SY)', ' Egypt', ' (EG)', '', ' Libya', ' (LY)', '', ' Tunisia', ' (TN)', ' Israel', ' (IL)', '', ' Morocco', ' (MA)', '', ' \xa0', ' \xa0', ' Jordan', ' (JO)', '', ' Palestine [2]', ' (PS)', '', ' \xa0', ' \xa0', ' Russia', ' (RU)', 'Argentina', '(AR)', '', 'China (except Hong Kong)', '(CN_X_HK)', '', 'Mexico', '(MX)', '', 'South Africa', '(ZA)', 'Australia', '(AU)', '', 'Hong Kong', '(HK)', '', 'Nigeria', '(NG)', '', 'South Korea', '(KR)', 'Brazil', '(BR)', '', 'India', '(IN)', '', 'New Zealand', '(NZ)', '', 'Taiwan', '(TW)', 'Canada', '(CA)', '', 'Japan', '(JP)', '', 'Singapore', '(SG)', '', 'United States', '(US)']

In [96]:
without_empty_strings = [string for string in clean_rows if string != ""]

In [97]:
print(without_empty_strings)

['Belgium', '(BE)', 'Greece', '(EL)', 'Lithuania', '(LT)', 'Portugal', '(PT)', 'Bulgaria', '(BG)', 'Spain', '(ES)', 'Luxembourg', '(LU)', 'Romania', '(RO)', 'Czechia', '(CZ)', 'France', '(FR)', 'Hungary', '(HU)', 'Slovenia', '(SI)', 'Denmark', '(DK)', 'Croatia', '(HR)', 'Malta', '(MT)', 'Slovakia', '(SK)', 'Germany', '(DE)', 'Italy', '(IT)', 'Netherlands', '(NL)', 'Finland', '(FI)', 'Estonia', '(EE)', 'Cyprus', '(CY)', 'Austria', '(AT)', 'Sweden', '(SE)', 'Ireland', '(IE)', 'Latvia', '(LV)', 'Poland', '(PL)', ' Iceland', ' (IS)', ' Norway', ' (NO)', ' Liechtenstein', ' (LI)', ' Switzerland', ' (CH)', ' United Kingdom', ' (UK)', ' Montenegro', ' (ME)', ' North Macedonia', ' (MK)', ' Albania', ' (AL)', 'Serbia', ' (RS)', ' Turkey', ' (TR)', ' Bosnia and Herzegovina', ' (BA)', ' Kosovo*', ' (XK[1])', ' Armenia', ' (AM)', ' Belarus', ' (BY)', ' Georgia', ' (GE)', ' Azerbaijan', ' (AZ)', ' Moldova', ' (MD)', ' Ukraine', ' (UA)', ' Algeria', ' (DZ)', ' Lebanon', ' (LB)', ' Syria', ' (SY)', ' Egypt', ' (EG)', ' Libya', ' (LY)', ' Tunisia', ' (TN)', ' Israel', ' (IL)', ' Morocco', ' (MA)', ' \xa0', ' \xa0', ' Jordan', ' (JO)', ' Palestine [2]', ' (PS)', ' \xa0', ' \xa0', ' Russia', ' (RU)', 'Argentina', '(AR)', 'China (except Hong Kong)', '(CN_X_HK)', 'Mexico', '(MX)', 'South Africa', '(ZA)', 'Australia', '(AU)', 'Hong Kong', '(HK)', 'Nigeria', '(NG)', 'South Korea', '(KR)', 'Brazil', '(BR)', 'India', '(IN)', 'New Zealand', '(NZ)', 'Taiwan', '(TW)', 'Canada', '(CA)', 'Japan', '(JP)', 'Singapore', '(SG)', 'United States', '(US)']

In [98]:
iter_strings = iter(without_empty_strings)

In [99]:
without_empty_strings

['Belgium',
 '(BE)',
 'Greece',
 '(EL)',
 'Lithuania',
 '(LT)',
 'Portugal',
 '(PT)',
 'Bulgaria',
 '(BG)',
 'Spain',
 '(ES)',
 'Luxembourg',
 '(LU)',
 'Romania',
 '(RO)',
 'Czechia',
 '(CZ)',
 'France',
 '(FR)',
 'Hungary',
 '(HU)',
 'Slovenia',
 '(SI)',
 'Denmark',
 '(DK)',
 'Croatia',
 '(HR)',
 'Malta',
 '(MT)',
 'Slovakia',
 '(SK)',
 'Germany',
 '(DE)',
 'Italy',
 '(IT)',
 'Netherlands',
 '(NL)',
 'Finland',
 '(FI)',
 'Estonia',
 '(EE)',
 'Cyprus',
 '(CY)',
 'Austria',
 '(AT)',
 'Sweden',
 '(SE)',
 'Ireland',
 '(IE)',
 'Latvia',
 '(LV)',
 'Poland',
 '(PL)',
 ' Iceland',
 ' (IS)',
 ' Norway',
 ' (NO)',
 ' Liechtenstein',
 ' (LI)',
 ' Switzerland',
 ' (CH)',
 ' United Kingdom',
 ' (UK)',
 ' Montenegro',
 ' (ME)',
 ' North Macedonia',
 ' (MK)',
 ' Albania',
 ' (AL)',
 'Serbia',
 ' (RS)',
 ' Turkey',
 ' (TR)',
 ' Bosnia and Herzegovina',
 ' (BA)',
 ' Kosovo*',
 ' (XK[1])',
 ' Armenia',
 ' (AM)',
 ' Belarus',
 ' (BY)',
 ' Georgia',
 ' (GE)',
 ' Azerbaijan',
 ' (AZ)',
 ' Moldova',
 ' (MD)',
 ' Ukraine',
 ' (UA)',
 ' Algeria',
 ' (DZ)',
 ' Lebanon',
 ' (LB)',
 ' Syria',
 ' (SY)',
 ' Egypt',
 ' (EG)',
 ' Libya',
 ' (LY)',
 ' Tunisia',
 ' (TN)',
 ' Israel',
 ' (IL)',
 ' Morocco',
 ' (MA)',
 ' \xa0',
 ' \xa0',
 ' Jordan',
 ' (JO)',
 ' Palestine [2]',
 ' (PS)',
 ' \xa0',
 ' \xa0',
 ' Russia',
 ' (RU)',
 'Argentina',
 '(AR)',
 'China (except Hong Kong)',
 '(CN_X_HK)',
 'Mexico',
 '(MX)',
 'South Africa',
 '(ZA)',
 'Australia',
 '(AU)',
 'Hong Kong',
 '(HK)',
 'Nigeria',
 '(NG)',
 'South Korea',
 '(KR)',
 'Brazil',
 '(BR)',
 'India',
 '(IN)',
 'New Zealand',
 '(NZ)',
 'Taiwan',
 '(TW)',
 'Canada',
 '(CA)',
 'Japan',
 '(JP)',
 'Singapore',
 '(SG)',
 'United States',
 '(US)']

In [100]:
country_code_name_pairs = [h + next(iter_strings, '') for h in iter_strings]

country_code_name_pairs

['Belgium(BE)',
 'Greece(EL)',
 'Lithuania(LT)',
 'Portugal(PT)',
 'Bulgaria(BG)',
 'Spain(ES)',
 'Luxembourg(LU)',
 'Romania(RO)',
 'Czechia(CZ)',
 'France(FR)',
 'Hungary(HU)',
 'Slovenia(SI)',
 'Denmark(DK)',
 'Croatia(HR)',
 'Malta(MT)',
 'Slovakia(SK)',
 'Germany(DE)',
 'Italy(IT)',
 'Netherlands(NL)',
 'Finland(FI)',
 'Estonia(EE)',
 'Cyprus(CY)',
 'Austria(AT)',
 'Sweden(SE)',
 'Ireland(IE)',
 'Latvia(LV)',
 'Poland(PL)',
 ' Iceland (IS)',
 ' Norway (NO)',
 ' Liechtenstein (LI)',
 ' Switzerland (CH)',
 ' United Kingdom (UK)',
 ' Montenegro (ME)',
 ' North Macedonia (MK)',
 ' Albania (AL)',
 'Serbia (RS)',
 ' Turkey (TR)',
 ' Bosnia and Herzegovina (BA)',
 ' Kosovo* (XK[1])',
 ' Armenia (AM)',
 ' Belarus (BY)',
 ' Georgia (GE)',
 ' Azerbaijan (AZ)',
 ' Moldova (MD)',
 ' Ukraine (UA)',
 ' Algeria (DZ)',
 ' Lebanon (LB)',
 ' Syria (SY)',
 ' Egypt (EG)',
 ' Libya (LY)',
 ' Tunisia (TN)',
 ' Israel (IL)',
 ' Morocco (MA)',
 ' \xa0 \xa0',
 ' Jordan (JO)',
 ' Palestine [2] (PS)',
 ' \xa0 \xa0',
 ' Russia (RU)',
 'Argentina(AR)',
 'China (except Hong Kong)(CN_X_HK)',
 'Mexico(MX)',
 'South Africa(ZA)',
 'Australia(AU)',
 'Hong Kong(HK)',
 'Nigeria(NG)',
 'South Korea(KR)',
 'Brazil(BR)',
 'India(IN)',
 'New Zealand(NZ)',
 'Taiwan(TW)',
 'Canada(CA)',
 'Japan(JP)',
 'Singapore(SG)',
 'United States(US)']

In [101]:
len(country_code_name_pairs)

74

In [102]:
country_code_name_pairs = [i for i in country_code_name_pairs if i  != ' \xa0 \xa0']

print(country_code_name_pairs)

['Belgium(BE)', 'Greece(EL)', 'Lithuania(LT)', 'Portugal(PT)', 'Bulgaria(BG)', 'Spain(ES)', 'Luxembourg(LU)', 'Romania(RO)', 'Czechia(CZ)', 'France(FR)', 'Hungary(HU)', 'Slovenia(SI)', 'Denmark(DK)', 'Croatia(HR)', 'Malta(MT)', 'Slovakia(SK)', 'Germany(DE)', 'Italy(IT)', 'Netherlands(NL)', 'Finland(FI)', 'Estonia(EE)', 'Cyprus(CY)', 'Austria(AT)', 'Sweden(SE)', 'Ireland(IE)', 'Latvia(LV)', 'Poland(PL)', ' Iceland (IS)', ' Norway (NO)', ' Liechtenstein (LI)', ' Switzerland (CH)', ' United Kingdom (UK)', ' Montenegro (ME)', ' North Macedonia (MK)', ' Albania (AL)', 'Serbia (RS)', ' Turkey (TR)', ' Bosnia and Herzegovina (BA)', ' Kosovo* (XK[1])', ' Armenia (AM)', ' Belarus (BY)', ' Georgia (GE)', ' Azerbaijan (AZ)', ' Moldova (MD)', ' Ukraine (UA)', ' Algeria (DZ)', ' Lebanon (LB)', ' Syria (SY)', ' Egypt (EG)', ' Libya (LY)', ' Tunisia (TN)', ' Israel (IL)', ' Morocco (MA)', ' Jordan (JO)', ' Palestine [2] (PS)', ' Russia (RU)', 'Argentina(AR)', 'China (except Hong Kong)(CN_X_HK)', 'Mexico(MX)', 'South Africa(ZA)', 'Australia(AU)', 'Hong Kong(HK)', 'Nigeria(NG)', 'South Korea(KR)', 'Brazil(BR)', 'India(IN)', 'New Zealand(NZ)', 'Taiwan(TW)', 'Canada(CA)', 'Japan(JP)', 'Singapore(SG)', 'United States(US)']

In [103]:
country_code_name_pairs = {x.replace("[1]", "") for x in country_code_name_pairs}
country_code_name_pairs = {x.replace("[2]", "") for x in country_code_name_pairs}
country_code_name_pairs = {x.replace("*", "") for x in country_code_name_pairs}

country_code_name_pairs

{' Albania (AL)',
 ' Algeria (DZ)',
 ' Armenia (AM)',
 ' Azerbaijan (AZ)',
 ' Belarus (BY)',
 ' Bosnia and Herzegovina (BA)',
 ' Egypt (EG)',
 ' Georgia (GE)',
 ' Iceland (IS)',
 ' Israel (IL)',
 ' Jordan (JO)',
 ' Kosovo (XK)',
 ' Lebanon (LB)',
 ' Libya (LY)',
 ' Liechtenstein (LI)',
 ' Moldova (MD)',
 ' Montenegro (ME)',
 ' Morocco (MA)',
 ' North Macedonia (MK)',
 ' Norway (NO)',
 ' Palestine  (PS)',
 ' Russia (RU)',
 ' Switzerland (CH)',
 ' Syria (SY)',
 ' Tunisia (TN)',
 ' Turkey (TR)',
 ' Ukraine (UA)',
 ' United Kingdom (UK)',
 'Argentina(AR)',
 'Australia(AU)',
 'Austria(AT)',
 'Belgium(BE)',
 'Brazil(BR)',
 'Bulgaria(BG)',
 'Canada(CA)',
 'China (except Hong Kong)(CN_X_HK)',
 'Croatia(HR)',
 'Cyprus(CY)',
 'Czechia(CZ)',
 'Denmark(DK)',
 'Estonia(EE)',
 'Finland(FI)',
 'France(FR)',
 'Germany(DE)',
 'Greece(EL)',
 'Hong Kong(HK)',
 'Hungary(HU)',
 'India(IN)',
 'Ireland(IE)',
 'Italy(IT)',
 'Japan(JP)',
 'Latvia(LV)',
 'Lithuania(LT)',
 'Luxembourg(LU)',
 'Malta(MT)',
 'Mexico(MX)',
 'Netherlands(NL)',
 'New Zealand(NZ)',
 'Nigeria(NG)',
 'Poland(PL)',
 'Portugal(PT)',
 'Romania(RO)',
 'Serbia (RS)',
 'Singapore(SG)',
 'Slovakia(SK)',
 'Slovenia(SI)',
 'South Africa(ZA)',
 'South Korea(KR)',
 'Spain(ES)',
 'Sweden(SE)',
 'Taiwan(TW)',
 'United States(US)'}

In [104]:
country_df = pd.DataFrame(country_code_name_pairs)

country_df

                   0
0    New Zealand(NZ)
1       Moldova (MD)
2       Portugal(PT)
3       Algeria (DZ)
4    Montenegro (ME)
..               ...
67  South Africa(ZA)
68        Taiwan(TW)
69        Latvia(LV)
70       Russia (RU)
71       Croatia(HR)

[72 rows x 1 columns]

In [105]:
country_df.columns =['country_name_and_acronym']

country_df

   country_name_and_acronym
0           New Zealand(NZ)
1              Moldova (MD)
2              Portugal(PT)
3              Algeria (DZ)
4           Montenegro (ME)
..                      ...
67         South Africa(ZA)
68               Taiwan(TW)
69               Latvia(LV)
70              Russia (RU)
71              Croatia(HR)

[72 rows x 1 columns]

In [106]:
country_df['dirty_country_acronym'] = country_df['country_name_and_acronym'].str.extract('(\(.+\))', expand=True)

country_df

   country_name_and_acronym dirty_country_acronym
0           New Zealand(NZ)                  (NZ)
1              Moldova (MD)                  (MD)
2              Portugal(PT)                  (PT)
3              Algeria (DZ)                  (DZ)
4           Montenegro (ME)                  (ME)
..                      ...                   ...
67         South Africa(ZA)                  (ZA)
68               Taiwan(TW)                  (TW)
69               Latvia(LV)                  (LV)
70              Russia (RU)                  (RU)
71              Croatia(HR)                  (HR)

[72 rows x 2 columns]

In [107]:
country_df['dirty_country_name'] = country_df['country_name_and_acronym'].str.extract('(^.+?(?=\())', expand=True)

country_df.tail(10)

   country_name_and_acronym dirty_country_acronym dirty_country_name
62             Morocco (MA)                  (MA)           Morocco
63            Argentina(AR)                  (AR)          Argentina
64               Greece(EL)                  (EL)             Greece
65               Mexico(MX)                  (MX)             Mexico
66              Hungary(HU)                  (HU)            Hungary
67         South Africa(ZA)                  (ZA)       South Africa
68               Taiwan(TW)                  (TW)             Taiwan
69               Latvia(LV)                  (LV)             Latvia
70              Russia (RU)                  (RU)            Russia
71              Croatia(HR)                  (HR)            Croatia

In [108]:
country_df['country_name'] = country_df['dirty_country_name'].str.lstrip().str.rstrip()

country_df['country_name']

0      New Zealand
1          Moldova
2         Portugal
3          Algeria
4       Montenegro
          ...
67    South Africa
68          Taiwan
69          Latvia
70          Russia
71         Croatia
Name: country_name, Length: 72, dtype: object

In [109]:
country_df['country_name'].unique()

array(['Russia', 'Norway', 'China', 'Moldova', 'Lebanon', 'Czechia',
       'Bulgaria', 'Switzerland', 'Albania', 'New Zealand',
       'South Africa', 'Brazil', 'Austria', 'Malta', 'Egypt', 'Estonia',
       'Israel', 'Germany', 'France', 'Finland', 'India', 'Poland',
       'Azerbaijan', 'Ukraine', 'Lithuania', 'Australia', 'Ireland',
       'Singapore', 'Denmark', 'Sweden', 'Taiwan', 'Armenia', 'Algeria',
       'Canada', 'Netherlands', 'United Kingdom', 'Kosovo', 'Mexico',
       'Palestine', 'Bosnia and Herzegovina', 'Iceland', 'Greece',
       'Serbia', 'Hong Kong', 'United States', 'Hungary', 'Georgia',
       'Latvia', 'Luxembourg', 'Liechtenstein', 'South Korea', 'Slovakia',
       'Japan', 'Turkey', 'Syria', 'Slovenia', 'Morocco', 'Croatia',
       'North Macedonia', 'Romania', 'Spain', 'Cyprus', 'Belarus',
       'Belgium', 'Nigeria', 'Montenegro', 'Jordan', 'Argentina',
       'Tunisia', 'Portugal', 'Libya', 'Italy'], dtype=object)

In [109]:
country_df['country_acronym'] = country_df['dirty_country_acronym'].str.extract('([A-Z]+)', expand=True)

country_df

,country_name_and_acronym,dirty_country_acronym,dirty_country_name,country_name,country_acronym
0,New Zealand(NZ),(NZ),New Zealand,New Zealand,NZ
1,Moldova (MD),(MD),Moldova,Moldova,MD
2,Portugal(PT),(PT),Portugal,Portugal,PT
3,Algeria (DZ),(DZ),Algeria,Algeria,DZ
4,Montenegro (ME),(ME),Montenegro,Montenegro,ME
...,...,...,...,...,...
67,South Africa(ZA),(ZA),South Africa,South Africa,ZA
68,Taiwan(TW),(TW),Taiwan,Taiwan,TW
69,Latvia(LV),(LV),Latvia,Latvia,LV
70,Russia (RU),(RU),Russia,Russia,RU
71,Croatia(HR),(HR),Croatia,Croatia,HR

In [110]:
country_df = country_df[['country_name','country_acronym']]

country_df

    country_name country_acronym
0    New Zealand              NZ
1        Moldova              MD
2       Portugal              PT
3        Algeria              DZ
4     Montenegro              ME
..           ...             ...
67  South Africa              ZA
68        Taiwan              TW
69        Latvia              LV
70        Russia              RU
71       Croatia              HR

[72 rows x 2 columns]

In [111]:
project_m1_cleaned_data['country_code'].unique()

array(['AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR',
       'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'MT', 'NL',
       'PL', 'PT', 'RO', 'SE', 'SI', 'SK'], dtype=object)

In [112]:
project_m1_cleaned_data = pd.merge(project_m1_cleaned_data, country_df, 'left', left_on=['country_code'], right_on=['country_acronym'])

project_m1_cleaned_data

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,lives in / area type,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst,job_description,country_name,country_acronym
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61,Male,NO,40_65,no education,NO,None,AT,Rural,I know something about it,I would not vote,None of the above,None of the above,None of the above,Unknown,Austria,AT
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57,Male,YES,40_65,high,YES,861a9b9151e11362eb3c77ca914172d0,AT,Urban,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working,Automatic Data Processing Planner,Austria,AT
2,83127080-da3d-0133-c74f-0a81e8b09a82,32,Male,NO,26_39,None,NO,None,AT,Urban,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...,Unknown,Austria,AT
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45,Male,YES,40_65,high,YES,049a3f3a2b5f85cb2971ba77ad66e10c,AT,Rural,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above,Data Coordinator,Austria,AT
4,24954a70-db98-0133-4a64-0a81e8b09a82,41,Female,YES,40_65,high,YES,f4b2fb1aa40f661488e2782b6d57ad2f,AT,Urban,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...,Database Developer,Austria,AT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37,Female,NO,26_39,high,YES,847165cfda6b1dc82ae22b967da8af2f,SK,Urban,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance,Data Warehouse Developer,Slovakia,SK
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53,Male,YES,40_65,high,YES,a4d5b8b38f9513825d0d94a981ebe962,SK,Urban,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...,Database Manager,Slovakia,SK
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,24,Male,NO,14_25,low,NO,None,SK,Urban,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above,Unknown,Slovakia,SK
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47,Male,YES,40_65,low,YES,775190277a849cba701b306a7b374c0a,SK,Urban,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...,Data Officer,Slovakia,SK
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51,Female,YES,40_65,high,YES,8a7a3f1bce0958ae9f090683e5a925b7,SK,Urban,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...,Data Scientist,Slovakia,SK