#### First, I will state the libraries needed to work in the project.

In [1]:
import pandas as pd

import pymysql

import numpy as np

from sqlalchemy import create_engine

#### Second, I will state explicitly the path, connection string and engine that will provide access to our raw data.

In [2]:
sqlitedb_abs_path = '/Users/manuelaquino/Bootcamp/project_m1/raw_data_project_m1.db'

connection_string = f'sqlite:///{sqlitedb_abs_path}'

engine = create_engine(connection_string)

#### Down here, I will just see my database tables and query "SELECT *" from each table. 
#### This allows me to confirm my connection and to take a first look at the data contained.

In [3]:
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", engine)

            name
0  personal_info
1   country_info
2    career_info
3      poll_info

In [4]:
pd.read_sql_query("SELECT * FROM personal_info", engine)

,uuid,age,gender,dem_has_children,age_group
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65
...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65

In [5]:
pd.read_sql_query("SELECT * FROM country_info", engine)

                                      uuid country_code        rural
0     f6e7ee00-deac-0133-4de8-0a81e8b09a82           AT  countryside
1     54f0f1c0-dda1-0133-a559-0a81e8b09a82           AT        urban
2     83127080-da3d-0133-c74f-0a81e8b09a82           AT         city
3     15626d40-db13-0133-ea5c-0a81e8b09a82           AT      Country
4     24954a70-db98-0133-4a64-0a81e8b09a82           AT         city
...                                    ...          ...          ...
9644  7d1ac020-dcb4-0133-817a-0a81e8b09a82           SK        urban
9645  39f989f0-db52-0133-8482-0a81e8b09a82           SK        urban
9646  70ce4a90-d965-0133-f5e4-0a81e8b09a82           SK    Non-Rural
9647  2896e440-db3c-0133-5b67-0a81e8b09a82           SK         city
9648  06217ba0-dd56-0133-edda-0a81e8b09a82           SK         city

[9649 rows x 3 columns]

In [6]:
pd.read_sql_query("SELECT * FROM career_info", engine)

,uuid,dem_education_level,dem_full_time_job,normalized_job_code
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,None
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,high,yes,861a9b9151e11362eb3c77ca914172d0
2,83127080-da3d-0133-c74f-0a81e8b09a82,None,no,None
3,15626d40-db13-0133-ea5c-0a81e8b09a82,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c
4,24954a70-db98-0133-4a64-0a81e8b09a82,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f
...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,high,yes,847165cfda6b1dc82ae22b967da8af2f
9645,39f989f0-db52-0133-8482-0a81e8b09a82,high,yes,a4d5b8b38f9513825d0d94a981ebe962
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,low,no,None
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,low,yes,775190277a849cba701b306a7b374c0a
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,high,yes,8a7a3f1bce0958ae9f090683e5a925b7

In [7]:
pd.read_sql_query("SELECT * FROM poll_info", engine)

,uuid,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,I have heard just a little about it,I would not vote,â€°Ã›_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,â€°Ã›_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,I understand it fully,I would probably vote for it,â€°Ã›_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,I have heard just a little about it,I would not vote,â€°Ã›_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

#### This step is done to JOIN all tables and start building what will be my first full raw dataframe.

In [8]:
project_m1_full_raw_data = pd.read_sql_query(
"""
SELECT * 
FROM personal_info
JOIN career_info
ON personal_info.uuid = career_info.uuid
JOIN country_info
ON country_info.uuid = career_info.uuid
JOIN poll_info
ON poll_info.uuid = career_info.uuid""", engine)

In [9]:
project_m1_full_raw_data

,uuid,age,gender,dem_has_children,age_group,uuid,dem_education_level,dem_full_time_job,normalized_job_code,uuid,country_code,rural,uuid,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,None,f6e7ee00-deac-0133-4de8-0a81e8b09a82,AT,countryside,f6e7ee00-deac-0133-4de8-0a81e8b09a82,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65,54f0f1c0-dda1-0133-a559-0a81e8b09a82,high,yes,861a9b9151e11362eb3c77ca914172d0,54f0f1c0-dda1-0133-a559-0a81e8b09a82,AT,urban,54f0f1c0-dda1-0133-a559-0a81e8b09a82,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39,83127080-da3d-0133-c74f-0a81e8b09a82,None,no,None,83127080-da3d-0133-c74f-0a81e8b09a82,AT,city,83127080-da3d-0133-c74f-0a81e8b09a82,I have heard just a little about it,I would not vote,â€°Ã›_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65,15626d40-db13-0133-ea5c-0a81e8b09a82,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,15626d40-db13-0133-ea5c-0a81e8b09a82,AT,Country,15626d40-db13-0133-ea5c-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,â€°Ã›_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65,24954a70-db98-0133-4a64-0a81e8b09a82,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,24954a70-db98-0133-4a64-0a81e8b09a82,AT,city,24954a70-db98-0133-4a64-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39,7d1ac020-dcb4-0133-817a-0a81e8b09a82,high,yes,847165cfda6b1dc82ae22b967da8af2f,7d1ac020-dcb4-0133-817a-0a81e8b09a82,SK,urban,7d1ac020-dcb4-0133-817a-0a81e8b09a82,I understand it fully,I would probably vote for it,â€°Ã›_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65,39f989f0-db52-0133-8482-0a81e8b09a82,high,yes,a4d5b8b38f9513825d0d94a981ebe962,39f989f0-db52-0133-8482-0a81e8b09a82,SK,urban,39f989f0-db52-0133-8482-0a81e8b09a82,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile,70ce4a90-d965-0133-f5e4-0a81e8b09a82,low,no,None,70ce4a90-d965-0133-f5e4-0a81e8b09a82,SK,Non-Rural,70ce4a90-d965-0133-f5e4-0a81e8b09a82,I have heard just a little about it,I would not vote,â€°Ã›_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65,2896e440-db3c-0133-5b67-0a81e8b09a82,low,yes,775190277a849cba701b306a7b374c0a,2896e440-db3c-0133-5b67-0a81e8b09a82,SK,city,2896e440-db3c-0133-5b67-0a81e8b09a82,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65,06217ba0-dd56-0133-edda-0a81e8b09a82,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,06217ba0-dd56-0133-edda-0a81e8b09a82,SK,city,06217ba0-dd56-0133-edda-0a81e8b09a82,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

In [10]:
type(project_m1_full_raw_data)

pandas.core.frame.DataFrame

#### As we can see, the 'uuid' column used to JOIN is beign repeated.
#### We will try to eliminate the duplicates and keep just one.

In [11]:
project_m1_full_raw_data.columns.unique()

Index(['uuid', 'age', 'gender', 'dem_has_children', 'age_group',
       'dem_education_level', 'dem_full_time_job', 'normalized_job_code',
       'country_code', 'rural', 'question_bbi_2016wave4_basicincome_awareness',
       'question_bbi_2016wave4_basicincome_vote',
       'question_bbi_2016wave4_basicincome_effect',
       'question_bbi_2016wave4_basicincome_argumentsfor',
       'question_bbi_2016wave4_basicincome_argumentsagainst'],
      dtype='object')

In [12]:
project_m1_data = project_m1_full_raw_data[['uuid', 'age', 'gender', 'dem_has_children', 'age_group',
       'dem_education_level', 'dem_full_time_job', 'normalized_job_code',
       'country_code', 'rural', 'question_bbi_2016wave4_basicincome_awareness',
       'question_bbi_2016wave4_basicincome_vote',
       'question_bbi_2016wave4_basicincome_effect',
       'question_bbi_2016wave4_basicincome_argumentsfor',
       'question_bbi_2016wave4_basicincome_argumentsagainst']]

In [13]:
project_m1_data = project_m1_data.loc[:,~project_m1_data.columns.duplicated()]

project_m1_data

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,rural,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65,no,no,None,AT,countryside,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65,high,yes,861a9b9151e11362eb3c77ca914172d0,AT,urban,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39,None,no,None,AT,city,I have heard just a little about it,I would not vote,â€°Ã›_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,AT,Country,I have heard just a little about it,I would probably vote for it,â€°Ã›_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,AT,city,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39,high,yes,847165cfda6b1dc82ae22b967da8af2f,SK,urban,I understand it fully,I would probably vote for it,â€°Ã›_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65,high,yes,a4d5b8b38f9513825d0d94a981ebe962,SK,urban,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile,low,no,None,SK,Non-Rural,I have heard just a little about it,I would not vote,â€°Ã›_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65,low,yes,775190277a849cba701b306a7b374c0a,SK,city,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,SK,city,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

#### The .unique() method allows me to explore the values inside a column to define a cleaning strategy.

In [14]:
project_m1_data['gender'].unique()

array(['male', 'Male', 'Fem', 'FeMale', 'female'], dtype=object)

#### Because there is a low quantity of distinc values, it's easy to identify the ones that need to be corrected and use the .replace() method to clean the inconsistent ones.

In [15]:
project_m1_data['gender'].replace(to_replace = "male", value ="Male", inplace = True)

In [16]:
project_m1_data['gender'].replace(to_replace =["Fem", "FeMale", "female"], value ="Female", inplace = True)

In [17]:
project_m1_data['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [18]:
print(project_m1_data['age'].unique().tolist())

['61 years old', '57 years old', '32 years old', '45 years old', '41 years old', '1990', '47 years old', '34 years old', '1994', '49 years old', '58 years old', '1991', '40 years old', '37 years old', '48 years old', '31 years old', '1999', '1989', '2001', '35 years old', '51 years old', '1988', '42 years old', '33 years old', '64 years old', '38 years old', '55 years old', '1992', '1993', '36 years old', '46 years old', '1998', '44 years old', '1996', '65 years old', '1995', '52 years old', '2002', '50 years old', '1997', '43 years old', '1987', '1986', '39 years old', '53 years old', '62 years old', '2000', '54 years old', '56 years old', '59 years old', '60 years old', '63 years old']

#### For this next step, regex proves useful to eliminate the unwanted part of the strings.

In [19]:
project_m1_cleaned_data = project_m1_data.replace(to_replace=' years old', value='', regex = True)

In [20]:
print(project_m1_cleaned_data['age'].unique())

['61' '57' '32' '45' '41' '1990' '47' '34' '1994' '49' '58' '1991' '40'
 '37' '48' '31' '1999' '1989' '2001' '35' '51' '1988' '42' '33' '64' '38'
 '55' '1992' '1993' '36' '46' '1998' '44' '1996' '65' '1995' '52' '2002'
 '50' '1997' '43' '1987' '1986' '39' '53' '62' '2000' '54' '56' '59' '60'
 '63']

In [21]:
len(project_m1_cleaned_data['age'][5])

4

#### I believe some string values appear to be the "YEAR OF BIRTH". I will substitute them by calculating age by year 2016.

- The number string will need to be converted to interger to support calculation.

In [22]:
project_m1_cleaned_data['age'] = project_m1_cleaned_data['age'].apply(lambda x: 2016 - int(x) if len(x) == 4 else x)

In [23]:
print(project_m1_cleaned_data['age'].unique())

['61' '57' '32' '45' '41' 26 '47' '34' 22 '49' '58' 25 '40' '37' '48' '31'
 17 27 15 '35' '51' 28 '42' '33' '64' '38' '55' 24 23 '36' '46' 18 '44' 20
 '65' 21 '52' 14 '50' 19 '43' 29 30 '39' '53' '62' 16 '54' '56' '59' '60'
 '63']

- I believe it's more convenient to convert this column to type interger/numeric because it will support more numeric operations and provide more information.

In [24]:
project_m1_cleaned_data['age'] = project_m1_cleaned_data['age'].astype(int)

In [25]:
print(project_m1_cleaned_data['age'].unique())

[61 57 32 45 41 26 47 34 22 49 58 25 40 37 48 31 17 27 15 35 51 28 42 33
 64 38 55 24 23 36 46 18 44 20 65 21 52 14 50 19 43 29 30 39 53 62 16 54
 56 59 60 63]

#### There are inconsistencies in the use of uppercase/lowercase size of characters on column ['dem_has_children'].
- Values will be made uppercase for consistency.

In [26]:
project_m1_cleaned_data['dem_has_children'] = project_m1_data['dem_has_children'].str.upper()

In [27]:
project_m1_data['age_group'].unique()

array(['40_65', '26_39', 'juvenile', '14_25'], dtype=object)

#### Looking at the unique values in ['age_group'] we detect one inconsistent one.
- By looking closer to the data I realized that all age values associated to 'juvenile' are inside the '14_25' range and should be placed in this bin.

In [28]:
juvenile = project_m1_cleaned_data[project_m1_cleaned_data['age_group'] == 'juvenile']

juvenile['age'].unique()

array([22, 17, 24, 20, 25, 14, 19, 23, 15, 16, 18, 21])

In [29]:
project_m1_cleaned_data['age_group'] = project_m1_data['age_group'].replace(to_replace = "juvenile", value ="14_25")

project_m1_cleaned_data['age_group'].unique()

array(['40_65', '26_39', '14_25'], dtype=object)

- To make sure values were placed correctly in each bin, I created a filter for each one and doubled checked numbers.

In [30]:
bin_14_25 = project_m1_cleaned_data[project_m1_cleaned_data['age_group'] == '14_25']

bin_26_39 = project_m1_cleaned_data[project_m1_cleaned_data['age_group'] == '26_39']

bin_40_65 = project_m1_cleaned_data[project_m1_cleaned_data['age_group'] == '40_65']

print('bin_14_25 =', bin_14_25['age'].unique())
print('bin_26_39 = ', bin_26_39['age'].unique())
print('bin_40_65 = ', bin_40_65['age'].unique())

bin_14_25 = [22 25 17 15 24 23 18 20 21 14 19 16]
bin_26_39 =  [32 26 34 37 31 27 35 28 33 38 36 29 30 39]
bin_40_65 =  [61 57 45 41 47 49 58 40 48 51 42 64 55 46 44 65 52 50 43 53 62 54 56 59
 60 63]

In [31]:
project_m1_data['dem_full_time_job'].unique()

array(['no', 'yes'], dtype=object)

In [32]:
project_m1_cleaned_data['dem_full_time_job'] = project_m1_data['dem_full_time_job'].str.upper()

#### For the ['rural'] column I think it should be ok to consolidate for only two values: 'urban' or 'rural'.
- rural = rural + countryside + Country
- urban = urban + city + Non-Rural

In [33]:
project_m1_data['rural'].unique()

array(['countryside', 'urban', 'city', 'Country', 'rural', 'Non-Rural'],
      dtype=object)

#### The data shows most of the people live in "urban/city" vs. "rural/countryside", and this is expected.

In [34]:
project_m1_data['rural'].value_counts()

urban          3842
city           1664
rural          1517
Non-Rural      1372
Country         772
countryside     482
Name: rural, dtype: int64

In [35]:
project_m1_data['rural'].replace(to_replace =["countryside", "Country"], value ="rural", inplace = True)
project_m1_data['rural'].replace(to_replace =["city", "Non-Rural"], value ="urban", inplace = True)

In [36]:
project_m1_data['rural'].value_counts()

urban    6878
rural    2771
Name: rural, dtype: int64

In [37]:
project_m1_cleaned_data['rural'] = project_m1_data['rural']

In [38]:
project_m1_cleaned_data['rural'].unique()

array(['rural', 'urban'], dtype=object)

#### I will change the column name from ['rural'] to ['lives in / area type'] because I think its a better description.

In [39]:
project_m1_cleaned_data = project_m1_cleaned_data.rename(columns = {"rural":"lives in / area type"})

In [40]:
project_m1_cleaned_data['lives in / area type'] = project_m1_cleaned_data['lives in / area type'].str.capitalize()

#### Looking at the unique() values inside the ['dem_education_level'] column. I realize we have some nulls/None.
- I checked the total amount of null values to determine if it's better to assume that nulls are probably a "Did not answer / No response" valid option. Or if I should place the nulls/None inside "no education".
- I believe adding 663 null values to "no education" its not necessarily the best way forward to improve data quality.

In [41]:
project_m1_data['dem_education_level'].unique()

array(['no', 'high', None, 'medium', 'low'], dtype=object)

In [42]:
project_m1_data['dem_education_level'].value_counts()

medium    3578
high      3270
low       1815
no         323
Name: dem_education_level, dtype: int64

In [43]:
project_m1_data['dem_education_level'].isnull().value_counts()

False    8986
True      663
Name: dem_education_level, dtype: int64

In [44]:
project_m1_data['dem_education_level'].replace(to_replace ="no", value ="no education", inplace = True)

In [45]:
project_m1_cleaned_data['dem_education_level'] = project_m1_data['dem_education_level']

In [46]:
project_m1_cleaned_data['dem_education_level'].unique()

array(['no education', 'high', None, 'medium', 'low'], dtype=object)

In [47]:
project_m1_cleaned_data[project_m1_data['dem_education_level'].isnull()].head(5)

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,lives in / area type,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
2,83127080-da3d-0133-c74f-0a81e8b09a82,32,Male,NO,26_39,None,NO,None,AT,Urban,I have heard just a little about it,I would not vote,â€°Ã›_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
23,b1eb3870-decd-0133-d783-0a81e8b09a82,25,Female,NO,14_25,None,YES,3833bd699e7afe4665b595f282da0387,AT,Rural,I know something about it,I would vote for it,A basic income would not affect my work choices,It reduces anxiety about financing basic needs...,It might encourage people to stop working
29,12cd5b70-dbd8-0133-0395-0a81e8b09a82,40,Male,YES,40_65,None,YES,dac2e921c1f887d9efc4c06fa33c1397,AT,Rural,I have never heard of it,I would vote for it,â€°Ã›_ work less,None of the above,None of the above
52,c76aa3e0-dbf6-0133-0d62-0a81e8b09a82,49,Male,YES,40_65,None,YES,847165cfda6b1dc82ae22b967da8af2f,AT,Rural,I know something about it,I would probably vote for it,â€°Ã›_ spend more time with my family,It encourages financial independence and self-...,It is impossible to finance
55,d4ac22b0-dd5d-0133-dd11-0a81e8b09a82,46,Female,YES,40_65,None,NO,None,AT,Rural,I know something about it,I would probably vote for it,None of the above,It creates more equality of opportunity | It r...,It might encourage people to stop working | It...

In [48]:
project_m1_cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9649 entries, 0 to 9648
Data columns (total 15 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   uuid                                                 9649 non-null   object
 1   age                                                  9649 non-null   int64
 2   gender                                               9649 non-null   object
 3   dem_has_children                                     9649 non-null   object
 4   age_group                                            9649 non-null   object
 5   dem_education_level                                  8986 non-null   object
 6   dem_full_time_job                                    9649 non-null   object
 7   normalized_job_code                                  5702 non-null   object
 8   country_code                                         9649 non-null   object
 9   lives in / area type                                 9649 non-null   object
 10  question_bbi_2016wave4_basicincome_awareness         9649 non-null   object
 11  question_bbi_2016wave4_basicincome_vote              9649 non-null   object
 12  question_bbi_2016wave4_basicincome_effect            9649 non-null   object
 13  question_bbi_2016wave4_basicincome_argumentsfor      9649 non-null   object
 14  question_bbi_2016wave4_basicincome_argumentsagainst  9649 non-null   object
dtypes: int64(1), object(14)
memory usage: 1.1+ MB

In [49]:
len(project_m1_data['normalized_job_code'].unique())

157

In [50]:
project_m1_cleaned_data['normalized_job_code'].value_counts()

775190277a849cba701b306a7b374c0a    101
049a3f3a2b5f85cb2971ba77ad66e10c     88
d4624ed8068d24948e18303212593cd6     88
dac2e921c1f887d9efc4c06fa33c1397     88
fcaf4aac737e53ad24b9f32f08b8740f     88
                                   ...
58eaf730050d2e23c7361fbb782e30a2      6
7aecc34a90868aac810bf3693b11534e      5
5285758deb04c98f58cbae2747195f33      5
b42566382f2d3deeca56d3667004fc9e      4
631bc3a12ed11340fc94ebfffa8f5f4e      4
Name: normalized_job_code, Length: 156, dtype: int64

In [51]:
project_m1_cleaned_data['question_bbi_2016wave4_basicincome_awareness'].value_counts()

I know something about it              3389
I understand it fully                  2389
I have heard just a little about it    2305
I have never heard of it               1566
Name: question_bbi_2016wave4_basicincome_awareness, dtype: int64

In [52]:
project_m1_cleaned_data['question_bbi_2016wave4_basicincome_vote'].value_counts()

I would probably vote for it        3272
I would vote for it                 2819
I would probably vote against it    1439
I would not vote                    1159
I would vote against it              960
Name: question_bbi_2016wave4_basicincome_vote, dtype: int64

In [53]:
project_m1_cleaned_data['question_bbi_2016wave4_basicincome_effect'].value_counts()

A basic income would not affect my work choices    3349
â€°Ã›_ spend more time with my family                 1387
None of the above                                  1227
â€°Ã›_ gain additional skills                          970
â€°Ã›_ look for a different job                        640
â€°Ã›_ work less                                       629
â€°Ã›_ do more volunteering work                       615
â€°Ã›_ work as a freelancer                            465
â€°Ã›_ stop working                                    367
Name: question_bbi_2016wave4_basicincome_effect, dtype: int64

In [54]:
project_m1_cleaned_data['question_bbi_2016wave4_basicincome_argumentsfor'].value_counts()

None of the above                                                                                                                                                                                                                                                                                                                           2163
It reduces anxiety about financing basic needs                                                                                                                                                                                                                                                                                              1273
It creates more equality of opportunity                                                                                                                                                                                                                                                                                                      848
It encourages financial independence and self-responsibility                                                                                                                                                                                                                                                                                 583
It increases solidarity, because it is funded by everyone                                                                                                                                                                                                                                                                                    479
                                                                                                                                                                                                                                                                                                                                            ...
It reduces bureaucracy and administrative expenses | It reduces anxiety about financing basic needs | It creates more equality of opportunity | It increases solidarity, because it is funded by everyone | It increases appreciation for household work and volunteering | It encourages financial independence and self-responsibility       1
It reduces bureaucracy and administrative expenses | It increases solidarity, because it is funded by everyone | It increases appreciation for household work and volunteering | It encourages financial independence and self-responsibility                                                                                                  1
It reduces anxiety about financing basic needs | It encourages financial independence and self-responsibility | It increases solidarity, because it is funded by everyone | It increases appreciation for household work and volunteering | It creates more equality of opportunity                                                            1
It increases solidarity, because it is funded by everyone | It creates more equality of opportunity | It reduces anxiety about financing basic needs | It reduces bureaucracy and administrative expenses | It increases appreciation for household work and volunteering | It encourages financial independence and self-responsibility       1
It increases solidarity, because it is funded by everyone | It encourages financial independence and self-responsibility | It reduces bureaucracy and administrative expenses | It increases appreciation for household work and volunteering                                                                                                  1
Name: question_bbi_2016wave4_basicincome_argumentsfor, Length: 674, dtype: int64

In [55]:
project_m1_cleaned_data['question_bbi_2016wave4_basicincome_argumentsagainst'].value_counts()

None of the above                                                                                                                                                                                                                                                                                                          1381
Only the people who need it most should get something from the state                                                                                                                                                                                                                                                        875
It might encourage people to stop working                                                                                                                                                                                                                                                                                   823
It is impossible to finance                                                                                                                                                                                                                                                                                                 767
Foreigners might come to my country and take advantage of the benefit                                                                                                                                                                                                                                                       632
                                                                                                                                                                                                                                                                                                                           ...
Foreigners might come to my country and take advantage of the benefit | It is impossible to finance | Only the people who need it most should get something from the state | It might encourage people to stop working | It is against the principle of linking merit and reward | It increases dependence on the state       1
Only the people who need it most should get something from the state | It might encourage people to stop working | It is against the principle of linking merit and reward | It is impossible to finance                                                                                                                      1
Only the people who need it most should get something from the state | It is impossible to finance | It might encourage people to stop working | It is against the principle of linking merit and reward | It increases dependence on the state | Foreigners might come to my country and take advantage of the benefit       1
Foreigners might come to my country and take advantage of the benefit | It is against the principle of linking merit and reward | It might encourage people to stop working | It is impossible to finance | Only the people who need it most should get something from the state                                              1
It increases dependence on the state | It is impossible to finance | It might encourage people to stop working | It is against the principle of linking merit and reward | Foreigners might come to my country and take advantage of the benefit | Only the people who need it most should get something from the state       1
Name: question_bbi_2016wave4_basicincome_argumentsagainst, Length: 881, dtype: int64

In [56]:
import requests

response = requests.get('http://api.dataatwork.org/v1/jobs?limit=500')

json_data = response.json()

len(json_data)

501

In [57]:
json_data[0:5]

[{'uuid': '26bc4486dfd0f60b3bb0d8d64e001800',
  'title': '1st Grade Teacher',
  'normalized_job_title': '1st grade teacher',
  'parent_uuid': '51cc95467c1844c7dc1d923265c023b2'},
 {'uuid': '9be6e14491305132c175cb1781a3356c',
  'title': '1st Pressman',
  'normalized_job_title': '1st pressman',
  'parent_uuid': '96f1cf15fe5880d8660c70f0756944ab'},
 {'uuid': 'd38d16bab3f9f25ae34ae3e2aad254d4',
  'title': '1st Pressman On Web Press',
  'normalized_job_title': '1st pressman on web press',
  'parent_uuid': '96f1cf15fe5880d8660c70f0756944ab'},
 {'uuid': '8576a78b5c1cae3a567ca7fd34500357',
  'title': '21 Dealer',
  'normalized_job_title': '21 dealer',
  'parent_uuid': '4be080220c824dcb435d59ebf1c3ce80'},
 {'uuid': 'a59278d7f653db37e54a270345a91a05',
  'title': '2nd Grade Teacher',
  'normalized_job_title': '2nd grade teacher',
  'parent_uuid': '51cc95467c1844c7dc1d923265c023b2'}]

In [58]:
dataatwork_api_response = requests.get('http://api.dataatwork.org/v1/jobs/861a9b9151e11362eb3c77ca914172d0')

In [59]:
dataatwork_api_response

In [60]:
json_dataatwork_api_response = dataatwork_api_response.json()

In [61]:
json_dataatwork_api_response

{'uuid': '861a9b9151e11362eb3c77ca914172d0',
 'title': 'Automatic Data Processing Planner',
 'normalized_job_title': 'automatic data processing planner',
 'parent_uuid': '0148f61d4227497728ce33490843d056'}

In [62]:
json_dataatwork_api_response['title']

'Automatic Data Processing Planner'

In [63]:
unique_job_codes_in_db = project_m1_cleaned_data['normalized_job_code'].unique()

In [64]:
unique_job_codes_in_db[0:5]

array([None, '861a9b9151e11362eb3c77ca914172d0',
       '049a3f3a2b5f85cb2971ba77ad66e10c',
       'f4b2fb1aa40f661488e2782b6d57ad2f',
       '27af8700f5577cec835acee2cb90a2ff'], dtype=object)

In [65]:
unique_job_code_list = list(unique_job_codes_in_db[1:])

In [66]:
unique_job_code_list[0:10]

['861a9b9151e11362eb3c77ca914172d0',
 '049a3f3a2b5f85cb2971ba77ad66e10c',
 'f4b2fb1aa40f661488e2782b6d57ad2f',
 '27af8700f5577cec835acee2cb90a2ff',
 'c1b670eba9ccb65e7c99f7da116d5b9c',
 'd71c4164c99a5f9bca773e755a72f40f',
 '2ee80cf30e2483dfe0947adc0428f8c5',
 '897ef18a9321616495831a4b4b0c1bb2',
 'a003702c0cea282e17967772dd83de5e',
 '04c82eae29e1c4a30eac0710b74ab276']

In [67]:
for job_code in unique_job_code_list[0:5]:
    job_code_response = requests.get(f'http://api.dataatwork.org/v1/jobs/{job_code}').json()
    print(job_code_response)

{'uuid': '861a9b9151e11362eb3c77ca914172d0', 'title': 'Automatic Data Processing Planner', 'normalized_job_title': 'automatic data processing planner', 'parent_uuid': '0148f61d4227497728ce33490843d056'}
{'uuid': '049a3f3a2b5f85cb2971ba77ad66e10c', 'title': 'Data Coordinator', 'normalized_job_title': 'data coordinator', 'parent_uuid': '0b9dd32a367f4562ec77b993053d1910'}
{'uuid': 'f4b2fb1aa40f661488e2782b6d57ad2f', 'title': 'Database Developer', 'normalized_job_title': 'database developer', 'parent_uuid': 'b90ca4df5690002377a7b0f1f3d40781'}
{'uuid': '27af8700f5577cec835acee2cb90a2ff', 'title': 'Data Entry Specialist', 'normalized_job_title': 'data entry specialist', 'parent_uuid': 'bf88358c56bb6cbe7eabec38ae333d19'}
{'uuid': 'c1b670eba9ccb65e7c99f7da116d5b9c', 'title': 'Database Architect', 'normalized_job_title': 'database architect', 'parent_uuid': '596226d5f9ef63de41a852826d483d19'}

In [68]:
for job_code in unique_job_code_list:
    job_code_response = requests.get(f'http://api.dataatwork.org/v1/jobs/{job_code}').json()
    print(job_code_response)
    print(job_code_response['uuid'])
    print(job_code_response['title'])
    break

{'uuid': '861a9b9151e11362eb3c77ca914172d0', 'title': 'Automatic Data Processing Planner', 'normalized_job_title': 'automatic data processing planner', 'parent_uuid': '0148f61d4227497728ce33490843d056'}
861a9b9151e11362eb3c77ca914172d0
Automatic Data Processing Planner

In [69]:
job_code_dict = {}

for job_code in unique_job_code_list:
    job_code_response = requests.get(f'http://api.dataatwork.org/v1/jobs/{job_code}').json()
    job_code_dict[job_code] = job_code_response['title']

job_code_dict

{'861a9b9151e11362eb3c77ca914172d0': 'Automatic Data Processing Planner',
 '049a3f3a2b5f85cb2971ba77ad66e10c': 'Data Coordinator',
 'f4b2fb1aa40f661488e2782b6d57ad2f': 'Database Developer',
 '27af8700f5577cec835acee2cb90a2ff': 'Data Entry Specialist',
 'c1b670eba9ccb65e7c99f7da116d5b9c': 'Database Architect',
 'd71c4164c99a5f9bca773e755a72f40f': 'Geographic Information Systems Database Administrator (GIS Database Administrator)',
 '2ee80cf30e2483dfe0947adc0428f8c5': 'Crime Data Specialist',
 '897ef18a9321616495831a4b4b0c1bb2': 'Data Communications Software Consultant',
 'a003702c0cea282e17967772dd83de5e': 'Data Security Analyst',
 '04c82eae29e1c4a30eac0710b74ab276': 'Database Marketing Analyst',
 'fcaf4aac737e53ad24b9f32f08b8740f': 'Computer or Data Processing Systems Consultant',
 '3833bd699e7afe4665b595f282da0387': 'Database Development and Administration Project Manager',
 '19e384e977796c25780d8c28b12089c4': 'Naval Tactical Data System--Combat Information Center Watch Officer, General',
 '474b962c13632a04e42a546be4f11dbb': 'Data Coder Operator',
 'dac2e921c1f887d9efc4c06fa33c1397': 'Automatic Data Processing Customer Liaison (ADP Customer Liaison)',
 '996da29c84f5eed00da40c230f4c4078': 'Data Entry Representative',
 'cc2b26cc436bea36bda3bdd7367c411a': 'Data Processing Auditor',
 '25fe195cbf915c0824fa6c44e6d0008c': 'Maintenance Data Analyst',
 '76385cb24e831b3364279b9de5641d8f': 'Automatic Data Processing Systems Security Specialist (ADP Systems Security)',
 '16b67d7f57698455aefbc1ae1b358b50': 'Database Engineer',
 'b24ece3300d2f8ab34f9553e531183d6': 'Data Processing Systems Project Planner',
 '5db2c8d6539f983e1ca3d7c5b939e190': 'Database Administration Associate',
 '36675c937946c8a4fc5de7d0b4c850de': 'Data Warehousing Engineer',
 '847165cfda6b1dc82ae22b967da8af2f': 'Data Warehouse Developer',
 '2ca138b991c50dc6696238e5ad800142': 'Database Software Technician',
 '775190277a849cba701b306a7b374c0a': 'Data Officer',
 '022d0e3a40aa3e29bca6851542b27842': 'Data Keyer',
 '375017ea3a1a97f5ea676def873bb25b': 'Geographic Information Systems Data Specialist (GIS Data Specialist)',
 '1dd2fdc8a3981f2a1d8f0ca173952bb8': 'Database Administration Manager',
 'e605336f5a43949cb6b18054fd1937f1': 'Database Security Expert',
 '800b621aab5dac18f4caef621fa43a49': 'Data Systems Manager',
 'd06dfb43c95b585a89ae556c9221b573': 'Data Warehousing Manager',
 'a12a16280e22220f9354333f6fe1b22a': 'Geographic Information Systems Data Administrator (GIS Data Administrator)',
 '477b53ef09d37f098d5ed74f47fcbaec': 'Data Base Design Analyst',
 'e2f68bf748aea2c7d2254550c0c92b23': 'Director of Data Operations',
 '45033f83b6e0309eca9bcd76917f15d0': 'Database Modeler',
 '141ddda0f613da65a280521247de0e9f': 'Data Administrator',
 '3ddea1b52e520996e4ec9fb70dc8b86b': 'Field Artillery Automated Tactical Data System Specialist',
 '6408c0d7c7faa4ced47fbc8474698126': 'Database Design Analyst',
 '07b7555fa790debaf5b04d1409ad5f11': 'Database Security Administrator',
 'a4d5b8b38f9513825d0d94a981ebe962': 'Database Manager',
 '5e93fd1a58c8a67b295f69d87d1a940d': 'Geographic Information Systems Data Manager (GIS Data Manager)',
 '122f24bc911a79c26ca66210557dda07': 'Clinical Data Specialist',
 '76b0ba6af40991629e20dff36edd02a5': 'Data Management Information Technology Specialist',
 '970eb38c7b3eb080466052ea994af189': 'Internet Database Specialist',
 'cf2d4db3c258faa2499bdeeeed6721a5': 'GPS Field Data Collector (Global Positioning System Field Data Collector)',
 '90c5430dbc810aec8695af2f1f4c42e8': 'Electronic Data Processing Auditor (EDP Auditor)',
 '7bb15eefb19ed09c59349baad7e8469e': 'Database Coordinator',
 'ec3d88b2fd083b870b8c5a603898ed39': 'Databases Computer Consultant',
 '1f8576bdffa64f492405d02b842c41a6': 'Data Management Associate',
 'edc64316da9707432443c7a4461abe6c': 'Data Security Administrator',
 '6cf4d336112984368f83181ac5ffe948': 'Health Data Analyst',
 'd4624ed8068d24948e18303212593cd6': 'Data Architect',
 '1a281bf4bd1fe9b2a6e464e508bea167': 'Data Storage Specialist',
 '2f704538f6c9d6459a97314be98124e2': 'Data Collector',
 '3161063d378eecc4581c5cdee46a2a6c': 'Head of Information Systems and Data Processing',
 '781f5d3a80812531fdc81125a527a626': 'Data Warehouse Specialist',
 '38a15ceadcdd6d4db16a88fa1a72b083': 'Data Warehouse Analyst',
 'e55556364d2096578fd153e9800e826f': 'Database Consultant',
 'd24ffac92c24fb0e7bd1abc5fc3b6254': 'Data Manager',
 'ccd7528fb38f16077360c5b67c9700c4': 'Data Communications Analyst',
 'f6fbd9dea1fa8f899683ade8e7d87d60': 'Data Entry Associate',
 '0de6170ccbed08e62b2e5862d5846a43': 'Database Tester',
 '499f9d9b6722342608656559b15abd90': 'Clinical Data Associate',
 '8a7a3f1bce0958ae9f090683e5a925b7': 'Data Scientist',
 '7acaed29536648e45ea2b82d45047fcf': 'Medical Data Analyst',
 '02e4c028f64f176de2f54bbc2f5403ce': 'Marketing Database Analyst',
 '569da68cdcac43a3b4a0126ea9170570': 'Database Designer',
 'ced804d972b03cca6d523ec8925a7943': 'Oracle Database Administrator (Oracle DBA)',
 '41b2978a2c07c5f477e60f26372d6c85': 'Database Management System Specialist (DBMS Specialist)',
 'd9e964a222fdd9527319ad88adbfaa2e': 'SQL Database Administrator',
 'ac47656fd51c2cd8037057262c910dc4': 'Data Processing Manager',
 'e49986dae76619a3941d280ee14d38ae': 'Data Miner',
 'f842344417ed2fc226d9cc00f9562458': 'Log Data Technician',
 '096536ec43ce2a7de73031b271a1c132': 'Flight Data Technician',
 'a33662485eb4ad97096183db945308f4': 'Automatic Data Processing Planner (ADP Planner)',
 '4f75f97ac5b5f00f9420074d501f0803': 'Data Capture Specialist',
 'f36c6ada3a808453a0bf241c74a4e994': 'Reference Data Expert',
 '41ba88cfd476ee8d5e3d9f7cea62f051': 'Data Recovery Planner',
 '894ca61c22718617c7e2404f582153da': 'Data Processing Consultant',
 '34d80517fe3bc143f9fc850386b8ffd7': 'Clinical Data Coordinator',
 'e7b3e1c6a32c7247cd4857e4c3574165': 'Data Processing Systems Analyst',
 '36ac256201657eeaa67ee95aaae3cd54': 'Data Warehousing Specialist',
 'bc6dcc49557388a9f53d6e642e73d7a2': 'Business Database Analyst',
 '00bff17fca67555d8d86e8ead86dcd70': 'Database Analyst',
 'b42566382f2d3deeca56d3667004fc9e': 'Data Center Manager',
 '7932d4705d002b47789c11edfaed685e': 'Data Control Assistant',
 'aee597cd78f235c9db9d3ca987c7c846': 'Database Development Project Manager',
 '1c37a6e2bf157c0eff4665c57c52602d': 'SCADA Technician (Supervisory Control and Data Acquisition Technician)',
 '46b09f5f86f1ed46a8cb8e14d41418c7': 'Survey Data Technician',
 'a2a9fbe67b4aa2b551ba0f3adac90a99': 'Engineer, System Electronic Data Processing (Engineer, System EDP)',
 '77d124811ae6887bd4ff42b0e2b49116': 'Data Warehouse Architect',
 'f05d2014d4a9adaab50fa1e0ca6f6c8c': 'Naval Tactical Data System--Combat Information Center Watch Officer, Carrier Controlled Approach Controller',
 'ac2588d5d7676a49bdcd038e4a0a0ec5': 'Data Compiler',
 '2173ff3afd8d28192f7cf119af201940': 'Data Modeling Specialist',
 'f5bc91b67dc30ad204158092116c4ed2': 'Clinical Data Manager',
 '433df1b945d32f17d9e61cf60a9bd06e': 'Data Abstractor',
 '1295a187473fd2f53427769fc7a4c02e': 'Clinical Data Management Associate Director',
 '004431b0c1ce29ff6145307fa23f3f98': 'Data Reduction Technician',
 '8fd068c8d9be73abfa678856177b6c40': 'Data Operations Director',
 'c34f03aa0a9c6edbe8ec50f4fa3687a8': 'Data Center Operator',
 '7aecc34a90868aac810bf3693b11534e': 'Clinical Trials Data Coordinator',
 '086f0063610283d1c23c44bca4ef92c0': 'Database Administrator (DBA)',
 '16b49a63ac3fcb90356c30187110ed94': 'Data Processing Auxiliary Equipment Operator',
 '437e4414c78611a270a5cedb4b4c0eed': 'Data Collection Technician',
 '679fb7003e0aedc14891fcd15dd846c5': 'Database Specialist',
 '7a37ddb38441873334fd8ff07c17ad22': 'Data Acquisition Technician',
 '58eaf730050d2e23c7361fbb782e30a2': 'Data Processing Mechanic',
 'd0abc47e83e7d85921e113f85175547a': 'Data Sciences Director',
 '73d251075a710326ae436d9819246377': 'Databases Software Consultant',
 '5e2bfe1fb8451158ff488c673535980c': 'Data Entry Machine Operator',
 'ac9f868b5c3e7cb3f31bcead5dadeb71': 'Micro Computer Data Processor',
 'f670246beda8187fbe875401e7bc4ba6': 'Data Processing Services Sales Representative',
 '0044971fda4a261b6049a63817913e95': 'Data Processing Equipment Repairer',
 'b36bc5f02fd641a126df999bcefa2777': 'Data Technician',
 '067c85859a63aa6f1c8c936904124dd6': 'Naval Tactical Data System--Combat Information Center Officer',
 '491d82be40d8395e347f9584124bccdd': 'Flight Test Data Acquisition Technician',
 '7028f15ad274cb4d9505101b9c1306b1': 'Clinical Data Management Manager (CDM Manager)',
 'fd69391dc29c83d5ad744daa57de0175': 'Data Transcriber',
 '3def30a9bc4356164176ba909f40bab8': 'Data Input Clerk',
 '132aa9e82c5d4c8a395342d0a6e22c5c': 'Electronic Data Interchange System Developer (EDI System Developer)',
 '07b2ace822aff5d35dcf5ea264ef3b59': 'Database Administration Project Manager',
 'f8984e50675cf61e5ac1ea8f661e0ab2': 'Field Traffic Data Technician',
 'd329d187dafb7546061ec7fbf137a2b4': 'Clinical Data Abstractor',
 'd63e35f948115e0c328a49db7bdb6e59': 'Data Control Clerk Supervisor',
 'bf7f43295d45cdced048c8126f977b6b': 'Datastage Developer',
 '6bf4290b983d58ce153af610008846c9': 'Data Entry Technician',
 'f1fc61f279e3ad14863e582ca6fdc473': 'Clinical Data Analyst',
 '31bf3181813e21ffdfd76b5881fab066': 'Data Entry Supervisor',
 '04b0eaf624b2deb45ccd62cf6ec7c7bc': 'Data Conversion Operator',
 '2616d64becb4f2c478dd42f501bbfbff': 'Data Processing Control Clerk',
 '776bf47111206d31ccf835650e1054cc': 'Data Typist',
 'c3b5ebd7b88c20786f11e87846c7d6ae': 'SCADA Operator (Supervisory Control and Data Acquisition Operator)',
 'dfea9e8bc3c565ff9e64d4288b1c423d': 'Customer Data Technician',
 'a50d1f4be063829950e6ddb02c91379f': 'Database Programmer',
 'af6630abd24c19f77cfba94aa4e3b7e1': 'Data Specialist',
 '901740e84d1a4760e440b039adac9df2': 'Data Processing Clerk',
 'f2ecf36d7eb0a4225974fc6c4f48cfcb': 'Voice and Data Technician',
 'f1fb62e4c97f4f5cd5001877cb94379e': 'Data Processor',
 'b9a57264eaada670703db113483ddfc3': 'Data Modeler',
 '65b92572bca68ff9c49c930749fa348c': 'LiDAR Data Analyst',
 '59dab7d0a3ee97d939aa8b1a8deec857': 'Data Management Manager',
 'afea0e0169a98ee264db2ddb1c6e6a34': 'Data Processing Supervisor',
 '0facaffe51cc1998a5fbdbe5fd18fd98': 'Weight in Motion Field Data Collection Technician',
 'ccf2c4daae069f054cada4c911819a17': 'Scientific Database Curator',
 '1426c924e1b6b162f6bfdd1906d98d0e': 'Operations Officer, Afloat (Naval Tactical Data Systems)',
 'eb3d789747d52df803ce63fe37bf53e9': 'Data Analyst',
 'bdf4dcd92089bc17345de83f4d06090f': 'Data Entry Operator',
 '5285758deb04c98f58cbae2747195f33': 'Data Reviewer',
 '04c27c76b463a917800549cf88a59961': 'Data Communications Technician',
 '631bc3a12ed11340fc94ebfffa8f5f4e': 'Database Technician',
 'b0fa6ede410f50b82ab74f5a705fe699': 'Analytical Data Miner',
 '559a21f836c93876f31b60e6d10656a7': 'Data Analysis Assistant',
 'c1fb1a01b78373ac2153c66fa08d16dc': 'Data Examination Clerk',
 '05bb9a333a66d6eb151e253623efe1c0': 'Data Entry Clerk',
 '4cee16550636e292b8d136486fce943b': 'Data Capture Clerk'}

In [70]:
job_code_df = pd.DataFrame.from_dict(job_code_dict, orient='index', columns=['job_description'])

job_code_df

                                                    job_description
861a9b9151e11362eb3c77ca914172d0  Automatic Data Processing Planner
049a3f3a2b5f85cb2971ba77ad66e10c                   Data Coordinator
f4b2fb1aa40f661488e2782b6d57ad2f                 Database Developer
27af8700f5577cec835acee2cb90a2ff              Data Entry Specialist
c1b670eba9ccb65e7c99f7da116d5b9c                 Database Architect
...                                                             ...
b0fa6ede410f50b82ab74f5a705fe699              Analytical Data Miner
559a21f836c93876f31b60e6d10656a7            Data Analysis Assistant
c1fb1a01b78373ac2153c66fa08d16dc             Data Examination Clerk
05bb9a333a66d6eb151e253623efe1c0                   Data Entry Clerk
4cee16550636e292b8d136486fce943b                 Data Capture Clerk

[156 rows x 1 columns]

In [71]:
job_code_df.columns

Index(['job_description'], dtype='object')

In [72]:
job_code_df.index

Index(['861a9b9151e11362eb3c77ca914172d0', '049a3f3a2b5f85cb2971ba77ad66e10c',
       'f4b2fb1aa40f661488e2782b6d57ad2f', '27af8700f5577cec835acee2cb90a2ff',
       'c1b670eba9ccb65e7c99f7da116d5b9c', 'd71c4164c99a5f9bca773e755a72f40f',
       '2ee80cf30e2483dfe0947adc0428f8c5', '897ef18a9321616495831a4b4b0c1bb2',
       'a003702c0cea282e17967772dd83de5e', '04c82eae29e1c4a30eac0710b74ab276',
       ...
       'eb3d789747d52df803ce63fe37bf53e9', 'bdf4dcd92089bc17345de83f4d06090f',
       '5285758deb04c98f58cbae2747195f33', '04c27c76b463a917800549cf88a59961',
       '631bc3a12ed11340fc94ebfffa8f5f4e', 'b0fa6ede410f50b82ab74f5a705fe699',
       '559a21f836c93876f31b60e6d10656a7', 'c1fb1a01b78373ac2153c66fa08d16dc',
       '05bb9a333a66d6eb151e253623efe1c0', '4cee16550636e292b8d136486fce943b'],
      dtype='object', length=156)

In [73]:
job_code_df = job_code_df.reset_index()

In [74]:
job_code_df.columns

Index(['index', 'job_description'], dtype='object')

In [75]:
job_code_df.index

RangeIndex(start=0, stop=156, step=1)

In [76]:
job_code_df

                                index                    job_description
0    861a9b9151e11362eb3c77ca914172d0  Automatic Data Processing Planner
1    049a3f3a2b5f85cb2971ba77ad66e10c                   Data Coordinator
2    f4b2fb1aa40f661488e2782b6d57ad2f                 Database Developer
3    27af8700f5577cec835acee2cb90a2ff              Data Entry Specialist
4    c1b670eba9ccb65e7c99f7da116d5b9c                 Database Architect
..                                ...                                ...
151  b0fa6ede410f50b82ab74f5a705fe699              Analytical Data Miner
152  559a21f836c93876f31b60e6d10656a7            Data Analysis Assistant
153  c1fb1a01b78373ac2153c66fa08d16dc             Data Examination Clerk
154  05bb9a333a66d6eb151e253623efe1c0                   Data Entry Clerk
155  4cee16550636e292b8d136486fce943b                 Data Capture Clerk

[156 rows x 2 columns]

In [77]:
job_code_df = job_code_df.rename(columns = {"index":"job_code"})

job_code_df

                             job_code                    job_description
0    861a9b9151e11362eb3c77ca914172d0  Automatic Data Processing Planner
1    049a3f3a2b5f85cb2971ba77ad66e10c                   Data Coordinator
2    f4b2fb1aa40f661488e2782b6d57ad2f                 Database Developer
3    27af8700f5577cec835acee2cb90a2ff              Data Entry Specialist
4    c1b670eba9ccb65e7c99f7da116d5b9c                 Database Architect
..                                ...                                ...
151  b0fa6ede410f50b82ab74f5a705fe699              Analytical Data Miner
152  559a21f836c93876f31b60e6d10656a7            Data Analysis Assistant
153  c1fb1a01b78373ac2153c66fa08d16dc             Data Examination Clerk
154  05bb9a333a66d6eb151e253623efe1c0                   Data Entry Clerk
155  4cee16550636e292b8d136486fce943b                 Data Capture Clerk

[156 rows x 2 columns]

In [78]:
project_m1_cleaned_data

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,lives in / area type,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61,Male,NO,40_65,no education,NO,None,AT,Rural,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57,Male,YES,40_65,high,YES,861a9b9151e11362eb3c77ca914172d0,AT,Urban,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32,Male,NO,26_39,None,NO,None,AT,Urban,I have heard just a little about it,I would not vote,â€°Ã›_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45,Male,YES,40_65,high,YES,049a3f3a2b5f85cb2971ba77ad66e10c,AT,Rural,I have heard just a little about it,I would probably vote for it,â€°Ã›_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41,Female,YES,40_65,high,YES,f4b2fb1aa40f661488e2782b6d57ad2f,AT,Urban,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37,Female,NO,26_39,high,YES,847165cfda6b1dc82ae22b967da8af2f,SK,Urban,I understand it fully,I would probably vote for it,â€°Ã›_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53,Male,YES,40_65,high,YES,a4d5b8b38f9513825d0d94a981ebe962,SK,Urban,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,24,Male,NO,14_25,low,NO,None,SK,Urban,I have heard just a little about it,I would not vote,â€°Ã›_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47,Male,YES,40_65,low,YES,775190277a849cba701b306a7b374c0a,SK,Urban,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51,Female,YES,40_65,high,YES,8a7a3f1bce0958ae9f090683e5a925b7,SK,Urban,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

In [79]:
project_m1_cleaned_data = pd.merge(project_m1_cleaned_data, job_code_df, 'left', left_on=['normalized_job_code'], right_on=['job_code'])

project_m1_cleaned_data

,uuid,age,gender,dem_has_children,age_group,dem_education_level,dem_full_time_job,normalized_job_code,country_code,lives in / area type,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst,job_code,job_description
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61,Male,NO,40_65,no education,NO,None,AT,Rural,I know something about it,I would not vote,None of the above,None of the above,None of the above,NaN,NaN
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57,Male,YES,40_65,high,YES,861a9b9151e11362eb3c77ca914172d0,AT,Urban,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working,861a9b9151e11362eb3c77ca914172d0,Automatic Data Processing Planner
2,83127080-da3d-0133-c74f-0a81e8b09a82,32,Male,NO,26_39,None,NO,None,AT,Urban,I have heard just a little about it,I would not vote,â€°Ã›_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...,NaN,NaN
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45,Male,YES,40_65,high,YES,049a3f3a2b5f85cb2971ba77ad66e10c,AT,Rural,I have heard just a little about it,I would probably vote for it,â€°Ã›_ work less,It reduces anxiety about financing basic needs,None of the above,049a3f3a2b5f85cb2971ba77ad66e10c,Data Coordinator
4,24954a70-db98-0133-4a64-0a81e8b09a82,41,Female,YES,40_65,high,YES,f4b2fb1aa40f661488e2782b6d57ad2f,AT,Urban,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...,f4b2fb1aa40f661488e2782b6d57ad2f,Database Developer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37,Female,NO,26_39,high,YES,847165cfda6b1dc82ae22b967da8af2f,SK,Urban,I understand it fully,I would probably vote for it,â€°Ã›_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance,847165cfda6b1dc82ae22b967da8af2f,Data Warehouse Developer
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53,Male,YES,40_65,high,YES,a4d5b8b38f9513825d0d94a981ebe962,SK,Urban,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...,a4d5b8b38f9513825d0d94a981ebe962,Database Manager
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,24,Male,NO,14_25,low,NO,None,SK,Urban,I have heard just a little about it,I would not vote,â€°Ã›_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above,NaN,NaN
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47,Male,YES,40_65,low,YES,775190277a849cba701b306a7b374c0a,SK,Urban,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...,775190277a849cba701b306a7b374c0a,Data Officer
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51,Female,YES,40_65,high,YES,8a7a3f1bce0958ae9f090683e5a925b7,SK,Urban,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...,8a7a3f1bce0958ae9f090683e5a925b7,Data Scientist